-- Generated by db/tools/build_migration.py; reviewed main 388f51d only.
-- Execute with a fail-fast versioned runner; never mysql --force. See db/README.md.
USE it_ticket_system;
SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET SESSION sql_mode = 'STRICT_ALL_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE TABLE IF NOT EXISTS schema_migration_audit (
 version VARCHAR(32) PRIMARY KEY, checksum CHAR(64) NOT NULL,
 operator_id VARCHAR(128) NOT NULL, source_timezone VARCHAR(64) NOT NULL,
 started_at DATETIME(6) NOT NULL, completed_at DATETIME(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS migration_v2_issue (
 issue_id BIGINT AUTO_INCREMENT PRIMARY KEY, entity_type VARCHAR(64) NOT NULL,
 legacy_id VARCHAR(128) NOT NULL, issue_code VARCHAR(128) NOT NULL,
 detail VARCHAR(2000) NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS migration_v2_counts (
 source_table VARCHAR(64) PRIMARY KEY, target_table VARCHAR(64) NOT NULL,
 source_rows BIGINT NOT NULL, staged_rows BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DELIMITER $$
CREATE PROCEDURE migration_v2_preflight()
BEGIN
 IF COALESCE(GET_LOCK(CONCAT(DATABASE(),'.schema_v2'),0),0)<>1 THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Another schema migration owns the advisory lock';
 END IF;
 IF COALESCE(@main_writes_stopped,0)<>1 OR COALESCE(@migration_operator,'')='' THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Require stopped writers and named migration operator';
 END IF;
 IF @main_source_utc_offset IS NULL OR CONVERT_TZ('2026-01-01 00:00:00',@main_source_utc_offset,'+00:00') IS NULL THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Set explicit verified main source UTC offset; timezone must not be guessed';
 END IF;
 IF EXISTS (SELECT 1 FROM schema_migration_audit WHERE version='V2_0') THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V2_0 already applied; do not replay';
 END IF;
END$$
DELIMITER ;
CALL migration_v2_preflight();
DROP PROCEDURE migration_v2_preflight;
INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'sla_instance',CAST(`sla_id` AS CHAR),'REQUIRES_REVIEWED_ADAPTER','Original target work seconds/calendar version/STOPPED meaning cannot be recovered; supply reviewed SLA adapter.' FROM `sla_instance` WHERE 1=1;

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'work_calendar',CAST(`id` AS CHAR),'REQUIRES_REVIEWED_ADAPTER','Per-date working intervals require reviewed conversion to versioned service calendar.' FROM `work_calendar` WHERE 1=1;

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'user',CAST(`user_id` AS CHAR),'UNKNOWN_STATUS','Unsupported status; explicit reviewed mapping required' FROM `user` WHERE `status` IS NOT NULL AND `status` NOT IN ('ACTIVE','DISABLED');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'user_role',CAST(`id` AS CHAR),'UNKNOWN_ROLE_CODE','Unsupported role_code; explicit reviewed mapping required' FROM `user_role` WHERE `role_code` IS NOT NULL AND `role_code` NOT IN ('EMPLOYEE','ENGINEER','PLATFORM_ADMIN','KB_ADMIN','KNOWLEDGE_ADMIN');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'support_team',CAST(`team_id` AS CHAR),'UNKNOWN_STATUS','Unsupported status; explicit reviewed mapping required' FROM `support_team` WHERE `status` IS NOT NULL AND `status` NOT IN ('ACTIVE','DISABLED');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'team_member',CAST(`id` AS CHAR),'UNKNOWN_STATUS','Unsupported status; explicit reviewed mapping required' FROM `team_member` WHERE `status` IS NOT NULL AND `status` NOT IN ('ACTIVE','DISABLED');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'category',CAST(`category_id` AS CHAR),'UNKNOWN_STATUS','Unsupported status; explicit reviewed mapping required' FROM `category` WHERE `status` IS NOT NULL AND `status` NOT IN ('ACTIVE','DISABLED');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'category',CAST(`category_id` AS CHAR),'UNKNOWN_TICKET_NATURE','Unsupported ticket_nature; explicit reviewed mapping required' FROM `category` WHERE `ticket_nature` IS NOT NULL AND `ticket_nature` NOT IN ('INCIDENT','SERVICE_REQUEST');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'ticket',CAST(`ticket_id` AS CHAR),'UNKNOWN_NATURE','Unsupported nature; explicit reviewed mapping required' FROM `ticket` WHERE `nature` IS NOT NULL AND `nature` NOT IN ('INCIDENT','SERVICE_REQUEST');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'ticket',CAST(`ticket_id` AS CHAR),'UNKNOWN_STATUS','Unsupported status; explicit reviewed mapping required' FROM `ticket` WHERE `status` IS NOT NULL AND `status` NOT IN ('NEW','ASSIGNED','IN_PROGRESS','PENDING_SUPPLEMENT','PENDING_EXTERNAL','PENDING_ACCEPTANCE','COMPLETED','CANCELLED','CLOSED');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'ticket',CAST(`ticket_id` AS CHAR),'UNKNOWN_PRIORITY','Unsupported priority; explicit reviewed mapping required' FROM `ticket` WHERE `priority` IS NOT NULL AND `priority` NOT IN ('HIGH','MEDIUM','LOW');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'ticket_draft',CAST(`draft_id` AS CHAR),'UNKNOWN_NATURE','Unsupported nature; explicit reviewed mapping required' FROM `ticket_draft` WHERE `nature` IS NOT NULL AND `nature` NOT IN ('INCIDENT','REQUEST','SERVICE_REQUEST');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'consultation',CAST(`session_id` AS CHAR),'UNKNOWN_SOURCE','Unsupported source; explicit reviewed mapping required' FROM `consultation` WHERE `source` IS NOT NULL AND `source` NOT IN ('AI','DIRECT_HUMAN','HUMAN_DIRECT','TICKET_FOLLOW_UP');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'consultation',CAST(`session_id` AS CHAR),'UNKNOWN_RESOLVED_TYPE','Unsupported resolved_type; explicit reviewed mapping required' FROM `consultation` WHERE `resolved_type` IS NOT NULL AND `resolved_type` NOT IN ('CONFIRMED','AUTO');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'consultation',CAST(`session_id` AS CHAR),'UNKNOWN_STATUS','Unsupported status; explicit reviewed mapping required' FROM `consultation` WHERE `status` IS NOT NULL AND `status` NOT IN ('AI_ACTIVE','WAITING_ENGINEER','HUMAN_ACTIVE','PENDING_CONFIRMATION','RESOLVED','CONVERTED_TO_TICKET','CLOSED');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'consultation_message',CAST(`message_id` AS CHAR),'UNKNOWN_SENDER_TYPE','Unsupported sender_type; explicit reviewed mapping required' FROM `consultation_message` WHERE `sender_type` IS NOT NULL AND `sender_type` NOT IN ('EMPLOYEE','ENGINEER','AI','SYSTEM');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'assignment',CAST(`assignment_id` AS CHAR),'UNKNOWN_END_REASON','Unsupported end_reason; explicit reviewed mapping required' FROM `assignment` WHERE `end_reason` IS NOT NULL AND `end_reason` NOT IN ('RESPONDED','TIMEOUT_TRANSFER','TRANSFER_APPLY','TIMEOUT','TRANSFERRED','CANCELLED','COMPLETED');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'sla_pause',CAST(`pause_id` AS CHAR),'UNKNOWN_REASON_TYPE','Unsupported reason_type; explicit reviewed mapping required' FROM `sla_pause` WHERE `reason_type` IS NOT NULL AND `reason_type` NOT IN ('SUPPLEMENT','EXTERNAL','PENDING_SUPPLEMENT','PENDING_EXTERNAL');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'notification',CAST(`notification_id` AS CHAR),'UNKNOWN_CHANNEL','Unsupported channel; explicit reviewed mapping required' FROM `notification` WHERE `channel` IS NOT NULL AND `channel` NOT IN ('INBOX','IN_APP','EMAIL');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'notification',CAST(`notification_id` AS CHAR),'UNKNOWN_STATUS','Unsupported status; explicit reviewed mapping required' FROM `notification` WHERE `status` IS NOT NULL AND `status` NOT IN ('PENDING','SENT','FAILED','DEAD_LETTER');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'knowledge_article',CAST(`article_id` AS CHAR),'UNKNOWN_STATUS','Unsupported status; explicit reviewed mapping required' FROM `knowledge_article` WHERE `status` IS NOT NULL AND `status` NOT IN ('DRAFT','PENDING_REVIEW','PUBLISHED','OFFLINE');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'knowledge_article',CAST(`article_id` AS CHAR),'UNKNOWN_RISK_LEVEL','Unsupported risk_level; explicit reviewed mapping required' FROM `knowledge_article` WHERE `risk_level` IS NOT NULL AND `risk_level` NOT IN ('NORMAL','HIGH');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'ai_interaction',CAST(`interaction_id` AS CHAR),'UNKNOWN_FEEDBACK','Unsupported feedback; explicit reviewed mapping required' FROM `ai_interaction` WHERE `feedback` IS NOT NULL AND `feedback` NOT IN ('HELPFUL','UNHELPFUL','WRONG','NOT_HELPFUL','INCORRECT');

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'user',CAST(user_id AS CHAR),'MISSING_DEPARTMENT','Identity source must supply department' FROM `user` WHERE department_id IS NULL;

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'knowledge_article',CAST(article_id AS CHAR),'MISSING_CATEGORY','Knowledge category must be reviewed' FROM `knowledge_article` WHERE category_id IS NULL;

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'ai_interaction',CAST(interaction_id AS CHAR),'INVALID_JSON','Retrieved versions are invalid JSON' FROM `ai_interaction` WHERE retrieved_versions IS NOT NULL AND NOT JSON_VALID(retrieved_versions);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'ticket_draft',CAST(draft_id AS CHAR),'DUPLICATE_ACTIVE_DRAFT','Explicitly select/archive drafts; never silently discard drafts' FROM `ticket_draft` WHERE user_id IN (SELECT user_id FROM ticket_draft GROUP BY user_id HAVING COUNT(*)>1);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'user_role',CAST(CAST(id AS CHAR) AS CHAR),'DUPLICATE_ROLE','Grant history needs reviewed canonical representation' FROM `user_role` WHERE user_id IN (SELECT user_id FROM user_role GROUP BY user_id,CASE role_code WHEN 'KB_ADMIN' THEN 'KNOWLEDGE_ADMIN' ELSE role_code END HAVING COUNT(*)>1);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'ticket',CAST(ticket_id AS CHAR),'ORPHAN_CREATOR','Ticket creator is absent' FROM `ticket` WHERE creator_id NOT IN (SELECT user_id FROM user);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'ticket',CAST(ticket_id AS CHAR),'ORPHAN_CATEGORY','Ticket category is absent' FROM `ticket` WHERE category_id NOT IN (SELECT category_id FROM category);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'ticket',CAST(ticket_id AS CHAR),'ORPHAN_ASSIGNEE','Ticket assignee is absent' FROM `ticket` WHERE assignee_id IS NOT NULL AND assignee_id NOT IN (SELECT user_id FROM user);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'user_role',CAST(`id` AS CHAR),'ORPHAN_USER_ID','user_id has no matching user record' FROM `user_role` WHERE `user_id` IS NOT NULL AND `user_id` NOT IN (SELECT `user_id` FROM `user`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'team_member',CAST(`id` AS CHAR),'ORPHAN_TEAM_ID','team_id has no matching support_team record' FROM `team_member` WHERE `team_id` IS NOT NULL AND `team_id` NOT IN (SELECT `team_id` FROM `support_team`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'team_member',CAST(`id` AS CHAR),'ORPHAN_ENGINEER_ID','engineer_id has no matching user record' FROM `team_member` WHERE `engineer_id` IS NOT NULL AND `engineer_id` NOT IN (SELECT `user_id` FROM `user`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'category',CAST(`category_id` AS CHAR),'ORPHAN_PARENT_ID','parent_id has no matching category record' FROM `category` WHERE `parent_id` IS NOT NULL AND `parent_id` NOT IN (SELECT `category_id` FROM `category`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'category_route',CAST(`id` AS CHAR),'ORPHAN_CATEGORY_ID','category_id has no matching category record' FROM `category_route` WHERE `category_id` IS NOT NULL AND `category_id` NOT IN (SELECT `category_id` FROM `category`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'category_route',CAST(`id` AS CHAR),'ORPHAN_TEAM_ID','team_id has no matching support_team record' FROM `category_route` WHERE `team_id` IS NOT NULL AND `team_id` NOT IN (SELECT `team_id` FROM `support_team`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'consultation',CAST(`session_id` AS CHAR),'ORPHAN_CREATOR_ID','creator_id has no matching user record' FROM `consultation` WHERE `creator_id` IS NOT NULL AND `creator_id` NOT IN (SELECT `user_id` FROM `user`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'consultation',CAST(`session_id` AS CHAR),'ORPHAN_CATEGORY_ID','category_id has no matching category record' FROM `consultation` WHERE `category_id` IS NOT NULL AND `category_id` NOT IN (SELECT `category_id` FROM `category`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'consultation',CAST(`session_id` AS CHAR),'ORPHAN_CURRENT_ENGINEER_ID','current_engineer_id has no matching user record' FROM `consultation` WHERE `current_engineer_id` IS NOT NULL AND `current_engineer_id` NOT IN (SELECT `user_id` FROM `user`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'consultation',CAST(`session_id` AS CHAR),'ORPHAN_TICKET_ID','ticket_id has no matching ticket record' FROM `consultation` WHERE `ticket_id` IS NOT NULL AND `ticket_id` NOT IN (SELECT `ticket_id` FROM `ticket`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'consultation_message',CAST(`message_id` AS CHAR),'ORPHAN_SESSION_ID','session_id has no matching consultation record' FROM `consultation_message` WHERE `session_id` IS NOT NULL AND `session_id` NOT IN (SELECT `session_id` FROM `consultation`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'ticket_transition',CAST(`transition_id` AS CHAR),'ORPHAN_TICKET_ID','ticket_id has no matching ticket record' FROM `ticket_transition` WHERE `ticket_id` IS NOT NULL AND `ticket_id` NOT IN (SELECT `ticket_id` FROM `ticket`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'ticket_draft',CAST(`draft_id` AS CHAR),'ORPHAN_USER_ID','user_id has no matching user record' FROM `ticket_draft` WHERE `user_id` IS NOT NULL AND `user_id` NOT IN (SELECT `user_id` FROM `user`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'assignment',CAST(`assignment_id` AS CHAR),'ORPHAN_ENGINEER_ID','engineer_id has no matching user record' FROM `assignment` WHERE `engineer_id` IS NOT NULL AND `engineer_id` NOT IN (SELECT `user_id` FROM `user`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'sla_pause',CAST(`pause_id` AS CHAR),'ORPHAN_SLA_ID','sla_id has no matching sla_instance record' FROM `sla_pause` WHERE `sla_id` IS NOT NULL AND `sla_id` NOT IN (SELECT `sla_id` FROM `sla_instance`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'notification',CAST(`notification_id` AS CHAR),'ORPHAN_RECEIVER_ID','receiver_id has no matching user record' FROM `notification` WHERE `receiver_id` IS NOT NULL AND `receiver_id` NOT IN (SELECT `user_id` FROM `user`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'knowledge_article',CAST(`article_id` AS CHAR),'ORPHAN_CATEGORY_ID','category_id has no matching category record' FROM `knowledge_article` WHERE `category_id` IS NOT NULL AND `category_id` NOT IN (SELECT `category_id` FROM `category`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'knowledge_article',CAST(`article_id` AS CHAR),'ORPHAN_CURRENT_VERSION_ID','current_version_id has no matching knowledge_version record' FROM `knowledge_article` WHERE `current_version_id` IS NOT NULL AND `current_version_id` NOT IN (SELECT `version_id` FROM `knowledge_version`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'knowledge_version',CAST(`version_id` AS CHAR),'ORPHAN_ARTICLE_ID','article_id has no matching knowledge_article record' FROM `knowledge_version` WHERE `article_id` IS NOT NULL AND `article_id` NOT IN (SELECT `article_id` FROM `knowledge_article`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'knowledge_version',CAST(`version_id` AS CHAR),'ORPHAN_AUTHOR_ID','author_id has no matching user record' FROM `knowledge_version` WHERE `author_id` IS NOT NULL AND `author_id` NOT IN (SELECT `user_id` FROM `user`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'knowledge_version',CAST(`version_id` AS CHAR),'ORPHAN_REVIEWER_ID','reviewer_id has no matching user record' FROM `knowledge_version` WHERE `reviewer_id` IS NOT NULL AND `reviewer_id` NOT IN (SELECT `user_id` FROM `user`);

INSERT INTO migration_v2_issue (entity_type,legacy_id,issue_code,detail) SELECT 'ai_interaction',CAST(`interaction_id` AS CHAR),'ORPHAN_SESSION_ID','session_id has no matching consultation record' FROM `ai_interaction` WHERE `session_id` IS NOT NULL AND `session_id` NOT IN (SELECT `session_id` FROM `consultation`);

SELECT entity_type,legacy_id,issue_code,detail FROM migration_v2_issue ORDER BY issue_id;
DELIMITER $$
CREATE PROCEDURE migration_v2_assert_clean()
BEGIN
 IF EXISTS (SELECT 1 FROM migration_v2_issue) THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Migration issues block staging; archive/review the report and provide a reviewed adapter';
 END IF;
END$$
DELIMITER ;
CALL migration_v2_assert_clean();
DROP PROCEDURE migration_v2_assert_clean;

CREATE TABLE IF NOT EXISTS v2_stage_user_account (
 user_id VARCHAR(64) PRIMARY KEY, employee_no VARCHAR(64) NOT NULL,
 display_name VARCHAR(255) NOT NULL, department_id VARCHAR(64) NOT NULL,
 identity_source VARCHAR(64) NOT NULL, enabled TINYINT(1) NOT NULL,
 last_identity_sync_at DATETIME(6), version BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_user_employee_no(employee_no), KEY idx_user_department(department_id),
 KEY idx_user_enabled(enabled),
  password_hash VARCHAR(100) COMMENT 'Compatibility: local BCrypt authentication; remove after SSO rollout'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_user_role (
 user_id VARCHAR(64) NOT NULL, role_code VARCHAR(32) NOT NULL,
 granted_by VARCHAR(64) NOT NULL, granted_at DATETIME(6) NOT NULL,
 revoked_at DATETIME(6), created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY(user_id,role_code), KEY idx_role_revoked(revoked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_support_team (
 team_id VARCHAR(64) PRIMARY KEY, name VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, UNIQUE KEY uk_team_name(name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_team_member (
 team_id VARCHAR(64) NOT NULL, engineer_id VARCHAR(64) NOT NULL,
 joined_at DATETIME(6) NOT NULL, left_at DATETIME(6), enabled TINYINT(1) NOT NULL,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY(team_id,engineer_id), KEY idx_member_engineer(engineer_id,enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_engineer_runtime_state (
 engineer_id VARCHAR(64) PRIMARY KEY, presence VARCHAR(32) NOT NULL,
 last_activity_at DATETIME(6), last_assigned_at DATETIME(6),
 version BIGINT NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, KEY idx_engineer_presence(presence,last_activity_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_engineer_category_capability (
 engineer_id VARCHAR(64) NOT NULL, category_id VARCHAR(64) NOT NULL,
 team_id VARCHAR(64) NOT NULL, enabled TINYINT(1) NOT NULL,
 effective_at DATETIME(6) NOT NULL, expired_at DATETIME(6),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY(engineer_id,category_id,team_id,effective_at),
 KEY idx_capability_route(category_id,team_id,enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_category (
 category_id VARCHAR(64) PRIMARY KEY, parent_id VARCHAR(64),
 nature VARCHAR(32) NOT NULL, name VARCHAR(255) NOT NULL, level SMALLINT NOT NULL,
 definition_version VARCHAR(64) NOT NULL, enabled TINYINT(1) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, KEY idx_category_parent(parent_id,level,enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_category_route (
 category_id VARCHAR(64) NOT NULL, team_id VARCHAR(64) NOT NULL,
 route_order INT NOT NULL, effective_at DATETIME(6) NOT NULL, expired_at DATETIME(6),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY(category_id,team_id,effective_at),
 UNIQUE KEY uk_route_order(category_id,route_order,effective_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_consultation (
 session_id VARCHAR(32) PRIMARY KEY, creator_id VARCHAR(64) NOT NULL,
 category_id VARCHAR(64), status VARCHAR(32) NOT NULL, current_engineer_id VARCHAR(64),
 source VARCHAR(32) NOT NULL, resolution_type VARCHAR(32), converted_ticket_id VARCHAR(32),
 closed_at DATETIME(6), version BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 KEY idx_consult_creator(creator_id,status,created_at),
 KEY idx_consult_engineer(current_engineer_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_consultation_message (
 message_id VARCHAR(64) PRIMARY KEY, session_id VARCHAR(32) NOT NULL,
 sender_id VARCHAR(64), sender_type VARCHAR(32) NOT NULL, client_message_id VARCHAR(64) NOT NULL,
 content MEDIUMTEXT NOT NULL,
 citation_json JSON, sent_at DATETIME(6) NOT NULL, withdrawn_at DATETIME(6),
 withdraw_reason VARCHAR(2000), created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 KEY idx_consult_message(session_id,sent_at,message_id),
 UNIQUE KEY uk_consult_client_message(session_id,client_message_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_ticket_draft (
 draft_id VARCHAR(64) PRIMARY KEY, creator_id VARCHAR(64) NOT NULL,
 nature VARCHAR(32), category_id VARCHAR(64), payload_json JSON NOT NULL,
 last_saved_at DATETIME(6) NOT NULL, expires_at DATETIME(6) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, UNIQUE KEY uk_active_draft(creator_id),
  title VARCHAR(100),
 description TEXT,
 impact_description TEXT,
 urgency_description TEXT,
 location VARCHAR(255),
 contact VARCHAR(255),
 asset_id VARCHAR(64)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_assignment (
 assignment_id VARCHAR(64) PRIMARY KEY, biz_type VARCHAR(32) NOT NULL,
 biz_id VARCHAR(64) NOT NULL, engineer_id VARCHAR(64) NOT NULL,
 assigned_at DATETIME(6) NOT NULL, response_deadline DATETIME(6),
 responded_at DATETIME(6), end_reason VARCHAR(32),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 KEY idx_assignment_object(biz_type,biz_id,assigned_at),
 KEY idx_assignment_engineer(engineer_id,end_reason)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_sla_instance (
 sla_id VARCHAR(64) PRIMARY KEY, biz_type VARCHAR(32) NOT NULL,
 biz_id VARCHAR(64) NOT NULL, sla_type VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL,
 target_work_seconds BIGINT NOT NULL, elapsed_work_seconds BIGINT NOT NULL DEFAULT 0,
 paused_seconds BIGINT NOT NULL DEFAULT 0, target_at DATETIME(6),
 breached_at DATETIME(6), met_at DATETIME(6), calendar_id VARCHAR(64) NOT NULL,
 calendar_version BIGINT NOT NULL, version BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_sla_business(biz_type,biz_id,sla_type),
 KEY idx_sla_due(status,target_at),
  priority_snapshot VARCHAR(32),
 near_breach_notified TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_sla_pause (
 pause_id VARCHAR(64) PRIMARY KEY, sla_id VARCHAR(64) NOT NULL,
 reason_type VARCHAR(32) NOT NULL, started_at DATETIME(6) NOT NULL,
 ended_at DATETIME(6), operator_id VARCHAR(64) NOT NULL,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 KEY idx_sla_pause(sla_id,started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_notification (
 notification_id VARCHAR(64) PRIMARY KEY, event_id VARCHAR(64) NOT NULL,
 receiver_id VARCHAR(64) NOT NULL, channel VARCHAR(32) NOT NULL,
 dedup_key VARCHAR(255) NOT NULL, status VARCHAR(32) NOT NULL,
 attempts INT NOT NULL DEFAULT 0, last_error VARCHAR(1000), sent_at DATETIME(6),
 read_at DATETIME(6), created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_notification_dedup(dedup_key), KEY idx_notification_receiver(receiver_id,status),
  title VARCHAR(100),
 content VARCHAR(500),
 action_url VARCHAR(200)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_audit_log (
 audit_id VARCHAR(64) PRIMARY KEY, actor_id VARCHAR(64), action VARCHAR(128) NOT NULL,
 object_type VARCHAR(64) NOT NULL, object_id VARCHAR(64) NOT NULL,
 before_json JSON, after_json JSON, reason VARCHAR(2000), request_id VARCHAR(128) NOT NULL,
 occurred_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 KEY idx_audit_object(object_type,object_id,occurred_at),
 KEY idx_audit_actor(actor_id,occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_idempotency_record (
 record_id VARCHAR(64) PRIMARY KEY, owner_id VARCHAR(64) NOT NULL,
 operation VARCHAR(128) NOT NULL, idempotency_key VARCHAR(128) NOT NULL,
 request_hash CHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, result_json JSON,
 expires_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_idempotency(owner_id,operation,idempotency_key),
 KEY idx_idempotency_expiry(expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_outbox_event (
 event_id VARCHAR(64) PRIMARY KEY, event_type VARCHAR(64) NOT NULL,
 aggregate_type VARCHAR(64) NOT NULL, aggregate_id VARCHAR(64) NOT NULL,
 event_version INT NOT NULL, aggregate_version BIGINT NOT NULL,
 payload_json JSON NOT NULL, status VARCHAR(32) NOT NULL,
 attempts INT NOT NULL DEFAULT 0, next_attempt_at DATETIME(6),
 published_at DATETIME(6), created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 KEY idx_outbox_publish(status,next_attempt_at),
 UNIQUE KEY uk_aggregate_version(aggregate_type,aggregate_id,aggregate_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_knowledge_article (
 article_id VARCHAR(64) PRIMARY KEY, status VARCHAR(32) NOT NULL,
 current_version_id VARCHAR(64), category_id VARCHAR(64) NOT NULL,
 risk_level VARCHAR(32) NOT NULL, version BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 KEY idx_knowledge_status(status,category_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_knowledge_version (
 version_id VARCHAR(64) PRIMARY KEY, article_id VARCHAR(64) NOT NULL,
 version_no INT NOT NULL, content_json JSON NOT NULL, author_id VARCHAR(64) NOT NULL,
 reviewer_id VARCHAR(64), published_at DATETIME(6), change_note VARCHAR(2000),
 platform_reviewer_id VARCHAR(64), platform_reviewed_at DATETIME(6),
 platform_review_decision VARCHAR(32),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_knowledge_version(article_id,version_no),
  search_text TEXT GENERATED ALWAYS AS (CONCAT_WS(' ', JSON_UNQUOTE(JSON_EXTRACT(content_json, '$.title')), JSON_UNQUOTE(JSON_EXTRACT(content_json, '$.summary')), JSON_UNQUOTE(JSON_EXTRACT(content_json, '$.keywords')), JSON_UNQUOTE(JSON_EXTRACT(content_json, '$.body')))) STORED,
 FULLTEXT KEY ft_knowledge_search(search_text) WITH PARSER ngram
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_ai_interaction (
 interaction_id VARCHAR(64) PRIMARY KEY, session_id VARCHAR(32) NOT NULL,
 model_version VARCHAR(128) NOT NULL, retrieved_versions_json JSON NOT NULL,
 confidence DECIMAL(8,4), feedback VARCHAR(32), latency_ms BIGINT NOT NULL,
 occurred_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, KEY idx_ai_session(session_id,occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_ticket (
  ticket_id VARCHAR(32) PRIMARY KEY, creator_id VARCHAR(64) NOT NULL,
  ticket_nature VARCHAR(32) NOT NULL, category_id VARCHAR(64) NOT NULL,
  title VARCHAR(100) NOT NULL, description TEXT NOT NULL,
  impact_description TEXT NOT NULL, urgency_description TEXT NOT NULL,
  location VARCHAR(255), contact VARCHAR(255), asset_id VARCHAR(64),
  status VARCHAR(32) NOT NULL, priority VARCHAR(32) NOT NULL,
  assignee_id VARCHAR(64), source_session_id VARCHAR(32),
  field_snapshot_json JSON, version BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
  completed_at DATETIME(6), closed_at DATETIME(6),
  KEY idx_ticket_creator_status (creator_id,status),
  KEY idx_ticket_assignee_status (assignee_id,status),
  KEY idx_ticket_priority_status (priority,status),
  category_snapshot VARCHAR(500),
 asset_check_status VARCHAR(32),
 impact_scope VARCHAR(32),
 urgency_level VARCHAR(32),
 auto_accepted TINYINT(1) NOT NULL DEFAULT 0,
 reopen_count INT NOT NULL DEFAULT 0,
 idempotency_key VARCHAR(128),
 first_response_at DATETIME(6),
 solved_at DATETIME(6),
 rating_score INT,
 rating_comment VARCHAR(2000),
 rated_at DATETIME(6),
 KEY idx_ticket_title_category(title,category_id,created_at),
 KEY idx_ticket_source_session(source_session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_ticket_transition (
  transition_id VARCHAR(64) PRIMARY KEY, ticket_id VARCHAR(32) NOT NULL,
  from_status VARCHAR(32), to_status VARCHAR(32) NOT NULL,
  event_code VARCHAR(64) NOT NULL, operator_id VARCHAR(64) NOT NULL,
  reason TEXT, occurred_at DATETIME(6) NOT NULL,
  UNIQUE KEY uk_transition_order (ticket_id,occurred_at,transition_id),
  KEY idx_transition_ticket (ticket_id,occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_service_calendar (
  calendar_id VARCHAR(64) PRIMARY KEY, timezone VARCHAR(64) NOT NULL,
  work_week_json JSON NOT NULL, work_intervals_json JSON NOT NULL,
  lunch_pauses TINYINT(1) NOT NULL DEFAULT 1, version BIGINT NOT NULL DEFAULT 0,
  effective_from DATETIME(6) NOT NULL, effective_to DATETIME(6),
  created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_calendar_holiday (
  holiday_id VARCHAR(64) PRIMARY KEY, calendar_id VARCHAR(64) NOT NULL,
  holiday_date DATE NOT NULL, name VARCHAR(255) NOT NULL,
  is_working_day TINYINT(1) NOT NULL DEFAULT 0,
  UNIQUE KEY uk_calendar_date (calendar_id,holiday_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v2_stage_exception_queue (
  exception_id VARCHAR(64) PRIMARY KEY, object_type VARCHAR(32) NOT NULL,
  object_id VARCHAR(64) NOT NULL, reason_code VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL, claimed_by VARCHAR(64), claimed_at DATETIME(6),
  resolved_by VARCHAR(64), resolved_at DATETIME(6), reason TEXT,
  created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
  KEY idx_exception_status (status,created_at),
  UNIQUE KEY uk_exception_open (object_type,object_id,reason_code,status),
  title VARCHAR(100),
 detail VARCHAR(1000),
 priority VARCHAR(32)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELIMITER $$
CREATE PROCEDURE migration_v2_copy()
BEGIN
 DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
 START TRANSACTION;
INSERT INTO `v2_stage_user_role` (`user_id`,`role_code`,`granted_by`,`granted_at`,`revoked_at`,`created_at`,`updated_at`)
SELECT s.`user_id`, CASE s.role_code WHEN 'KB_ADMIN' THEN 'KNOWLEDGE_ADMIN' ELSE s.role_code END, COALESCE(s.granted_by,'SYSTEM'), CONVERT_TZ(s.`granted_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.`revoked_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.`created_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.created_at, @main_source_utc_offset, '+00:00')
FROM `user_role` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'user_role','user_role',(SELECT COUNT(*) FROM `user_role`),(SELECT COUNT(*) FROM `v2_stage_user_role`);
INSERT INTO `v2_stage_support_team` (`team_id`,`name`,`enabled`,`version`,`created_at`,`updated_at`)
SELECT s.`team_id`, s.`name`, s.status='ACTIVE', 0, CONVERT_TZ(s.`created_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.`updated_at`, @main_source_utc_offset, '+00:00')
FROM `support_team` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'support_team','support_team',(SELECT COUNT(*) FROM `support_team`),(SELECT COUNT(*) FROM `v2_stage_support_team`);
INSERT INTO `v2_stage_team_member` (`team_id`,`engineer_id`,`joined_at`,`left_at`,`enabled`,`created_at`,`updated_at`)
SELECT s.`team_id`, s.`engineer_id`, CONVERT_TZ(s.`joined_at`, @main_source_utc_offset, '+00:00'), NULL, s.status='ACTIVE', CONVERT_TZ(s.`created_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.created_at, @main_source_utc_offset, '+00:00')
FROM `team_member` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'team_member','team_member',(SELECT COUNT(*) FROM `team_member`),(SELECT COUNT(*) FROM `v2_stage_team_member`);
INSERT INTO `v2_stage_category` (`category_id`,`parent_id`,`nature`,`name`,`level`,`definition_version`,`enabled`,`version`,`created_at`,`updated_at`)
SELECT s.`category_id`, s.`parent_id`, s.ticket_nature, s.`name`, s.`level`, 'legacy-main-v1', s.status='ACTIVE', s.`version`, CONVERT_TZ(s.`created_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.`updated_at`, @main_source_utc_offset, '+00:00')
FROM `category` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'category','category',(SELECT COUNT(*) FROM `category`),(SELECT COUNT(*) FROM `v2_stage_category`);
INSERT INTO `v2_stage_category_route` (`category_id`,`team_id`,`route_order`,`effective_at`,`expired_at`,`created_at`,`updated_at`)
SELECT s.`category_id`, s.`team_id`, s.`route_order`, CONVERT_TZ(s.`effective_at`, @main_source_utc_offset, '+00:00'), NULL, CONVERT_TZ(s.`created_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.created_at, @main_source_utc_offset, '+00:00')
FROM `category_route` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'category_route','category_route',(SELECT COUNT(*) FROM `category_route`),(SELECT COUNT(*) FROM `v2_stage_category_route`);
INSERT INTO `v2_stage_consultation` (`session_id`,`creator_id`,`category_id`,`status`,`current_engineer_id`,`source`,`resolution_type`,`converted_ticket_id`,`closed_at`,`version`,`created_at`,`updated_at`)
SELECT s.`session_id`, s.`creator_id`, s.`category_id`, s.`status`, s.`current_engineer_id`, CASE s.source WHEN 'DIRECT_HUMAN' THEN 'HUMAN_DIRECT' ELSE s.source END, CASE s.resolved_type WHEN 'CONFIRMED' THEN 'EMPLOYEE_CONFIRMED' WHEN 'AUTO' THEN 'AUTO_RESOLVED' ELSE NULL END, s.ticket_id, CONVERT_TZ(CASE WHEN s.status='CLOSED' THEN s.updated_at END, @main_source_utc_offset, '+00:00'), 0, CONVERT_TZ(s.`created_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.`updated_at`, @main_source_utc_offset, '+00:00')
FROM `consultation` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'consultation','consultation',(SELECT COUNT(*) FROM `consultation`),(SELECT COUNT(*) FROM `v2_stage_consultation`);
INSERT INTO `v2_stage_consultation_message` (`message_id`,`session_id`,`sender_id`,`sender_type`,`client_message_id`,`content`,`citation_json`,`sent_at`,`withdrawn_at`,`withdraw_reason`,`created_at`,`updated_at`)
SELECT s.`message_id`, s.`session_id`, s.`sender_id`, s.`sender_type`, CONCAT('legacy-',s.message_id), s.`content`, NULL, CONVERT_TZ(s.created_at, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.`withdrawn_at`, @main_source_utc_offset, '+00:00'), NULL, CONVERT_TZ(s.`created_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.created_at, @main_source_utc_offset, '+00:00')
FROM `consultation_message` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'consultation_message','consultation_message',(SELECT COUNT(*) FROM `consultation_message`),(SELECT COUNT(*) FROM `v2_stage_consultation_message`);
INSERT INTO `v2_stage_ticket_draft` (`draft_id`,`creator_id`,`nature`,`category_id`,`payload_json`,`last_saved_at`,`expires_at`,`version`,`created_at`,`updated_at`,`title`,`description`,`impact_description`,`urgency_description`,`location`,`contact`,`asset_id`)
SELECT s.`draft_id`, s.user_id, CASE s.nature WHEN 'REQUEST' THEN 'SERVICE_REQUEST' ELSE s.nature END, s.`category_id`, JSON_OBJECT('ticketNature', CASE s.nature WHEN 'REQUEST' THEN 'SERVICE_REQUEST' ELSE s.nature END, 'categoryId',s.category_id,'title',s.title,'description',s.description,'impactDescription',s.impact_description,'urgencyDescription',s.urgency_description,'location',s.location,'contact',s.contact,'assetId',s.asset_id), CONVERT_TZ(s.updated_at, @main_source_utc_offset, '+00:00'), DATE_ADD(CONVERT_TZ(s.updated_at, @main_source_utc_offset, '+00:00'), INTERVAL 7 DAY), 0, CONVERT_TZ(s.updated_at, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.`updated_at`, @main_source_utc_offset, '+00:00'), s.`title`, s.`description`, s.`impact_description`, s.`urgency_description`, s.`location`, s.`contact`, s.`asset_id`
FROM `ticket_draft` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'ticket_draft','ticket_draft',(SELECT COUNT(*) FROM `ticket_draft`),(SELECT COUNT(*) FROM `v2_stage_ticket_draft`);
INSERT INTO `v2_stage_assignment` (`assignment_id`,`biz_type`,`biz_id`,`engineer_id`,`assigned_at`,`response_deadline`,`responded_at`,`end_reason`,`created_at`,`updated_at`)
SELECT s.`assignment_id`, s.`biz_type`, s.`biz_id`, s.`engineer_id`, CONVERT_TZ(s.`assigned_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.`response_deadline`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.`responded_at`, @main_source_utc_offset, '+00:00'), CASE s.end_reason WHEN 'TIMEOUT_TRANSFER' THEN 'TIMEOUT' WHEN 'TRANSFER_APPLY' THEN 'TRANSFERRED' ELSE s.end_reason END, CONVERT_TZ(s.`created_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.created_at, @main_source_utc_offset, '+00:00')
FROM `assignment` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'assignment','assignment',(SELECT COUNT(*) FROM `assignment`),(SELECT COUNT(*) FROM `v2_stage_assignment`);
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'sla_instance','sla_instance',(SELECT COUNT(*) FROM `sla_instance`),(SELECT COUNT(*) FROM `v2_stage_sla_instance`);
INSERT INTO `v2_stage_sla_pause` (`pause_id`,`sla_id`,`reason_type`,`started_at`,`ended_at`,`operator_id`,`created_at`,`updated_at`)
SELECT s.`pause_id`, s.`sla_id`, CASE s.reason_type WHEN 'SUPPLEMENT' THEN 'PENDING_SUPPLEMENT' WHEN 'EXTERNAL' THEN 'PENDING_EXTERNAL' ELSE s.reason_type END, CONVERT_TZ(s.`started_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.`ended_at`, @main_source_utc_offset, '+00:00'), s.`operator_id`, CONVERT_TZ(s.started_at, @main_source_utc_offset, '+00:00'), CONVERT_TZ(COALESCE(s.ended_at,s.started_at), @main_source_utc_offset, '+00:00')
FROM `sla_pause` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'sla_pause','sla_pause',(SELECT COUNT(*) FROM `sla_pause`),(SELECT COUNT(*) FROM `v2_stage_sla_pause`);
INSERT INTO `v2_stage_notification` (`notification_id`,`event_id`,`receiver_id`,`channel`,`dedup_key`,`status`,`attempts`,`last_error`,`sent_at`,`read_at`,`created_at`,`updated_at`,`title`,`content`,`action_url`)
SELECT s.`notification_id`, s.`event_id`, s.`receiver_id`, CASE s.channel WHEN 'INBOX' THEN 'IN_APP' ELSE s.channel END, s.`dedup_key`, s.`status`, s.`attempts`, s.`last_error`, NULL, NULL, CONVERT_TZ(s.`created_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.`updated_at`, @main_source_utc_offset, '+00:00'), s.`title`, s.`content`, s.`action_url`
FROM `notification` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'notification','notification',(SELECT COUNT(*) FROM `notification`),(SELECT COUNT(*) FROM `v2_stage_notification`);
INSERT INTO `v2_stage_audit_log` (`audit_id`,`actor_id`,`action`,`object_type`,`object_id`,`before_json`,`after_json`,`reason`,`request_id`,`occurred_at`,`created_at`,`updated_at`)
SELECT CAST(s.audit_id AS CHAR), s.`actor_id`, s.`action`, s.`object_type`, s.`object_id`, CASE WHEN s.before_value IS NULL THEN NULL WHEN JSON_VALID(s.before_value) THEN CAST(s.before_value AS JSON) ELSE JSON_OBJECT('legacyText',s.before_value) END, CASE WHEN s.after_value IS NULL THEN NULL WHEN JSON_VALID(s.after_value) THEN CAST(s.after_value AS JSON) ELSE JSON_OBJECT('legacyText',s.after_value) END, s.`reason`, COALESCE(s.request_id,CONCAT('legacy-main-audit-',s.audit_id)), CONVERT_TZ(s.`occurred_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.occurred_at, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.occurred_at, @main_source_utc_offset, '+00:00')
FROM `audit_log` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'audit_log','audit_log',(SELECT COUNT(*) FROM `audit_log`),(SELECT COUNT(*) FROM `v2_stage_audit_log`);
INSERT INTO `v2_stage_knowledge_article` (`article_id`,`status`,`current_version_id`,`category_id`,`risk_level`,`version`,`created_at`,`updated_at`)
SELECT s.`article_id`, s.`status`, s.`current_version_id`, s.`category_id`, s.`risk_level`, 0, CONVERT_TZ(s.`created_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.`updated_at`, @main_source_utc_offset, '+00:00')
FROM `knowledge_article` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'knowledge_article','knowledge_article',(SELECT COUNT(*) FROM `knowledge_article`),(SELECT COUNT(*) FROM `v2_stage_knowledge_article`);
INSERT INTO `v2_stage_knowledge_version` (`version_id`,`article_id`,`version_no`,`content_json`,`author_id`,`reviewer_id`,`published_at`,`change_note`,`platform_reviewer_id`,`platform_reviewed_at`,`platform_review_decision`,`created_at`,`updated_at`)
SELECT s.`version_id`, s.`article_id`, s.`version_no`, JSON_OBJECT('title',s.title,'body',s.content), s.`author_id`, s.`reviewer_id`, CONVERT_TZ(s.`published_at`, @main_source_utc_offset, '+00:00'), s.`change_note`, s.recheck_by, NULL, NULL, CONVERT_TZ(s.`created_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.created_at, @main_source_utc_offset, '+00:00')
FROM `knowledge_version` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'knowledge_version','knowledge_version',(SELECT COUNT(*) FROM `knowledge_version`),(SELECT COUNT(*) FROM `v2_stage_knowledge_version`);
INSERT INTO `v2_stage_ai_interaction` (`interaction_id`,`session_id`,`model_version`,`retrieved_versions_json`,`confidence`,`feedback`,`latency_ms`,`occurred_at`,`created_at`,`updated_at`)
SELECT s.`interaction_id`, s.`session_id`, s.`model_version`, COALESCE(CAST(s.retrieved_versions AS JSON),JSON_ARRAY()), s.`confidence`, CASE s.feedback WHEN 'UNHELPFUL' THEN 'NOT_HELPFUL' WHEN 'WRONG' THEN 'INCORRECT' ELSE s.feedback END, COALESCE(s.latency,0), CONVERT_TZ(s.created_at, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.`created_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.created_at, @main_source_utc_offset, '+00:00')
FROM `ai_interaction` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'ai_interaction','ai_interaction',(SELECT COUNT(*) FROM `ai_interaction`),(SELECT COUNT(*) FROM `v2_stage_ai_interaction`);
INSERT INTO `v2_stage_ticket` (`ticket_id`,`creator_id`,`ticket_nature`,`category_id`,`title`,`description`,`impact_description`,`urgency_description`,`location`,`contact`,`asset_id`,`status`,`priority`,`assignee_id`,`source_session_id`,`field_snapshot_json`,`version`,`created_at`,`updated_at`,`completed_at`,`closed_at`,`category_snapshot`,`asset_check_status`,`impact_scope`,`urgency_level`,`auto_accepted`,`reopen_count`,`idempotency_key`,`first_response_at`,`solved_at`,`rating_score`,`rating_comment`,`rated_at`)
SELECT s.`ticket_id`, s.`creator_id`, s.nature, s.`category_id`, s.`title`, s.`description`, s.`impact_description`, s.`urgency_description`, s.`location`, s.`contact`, s.`asset_id`, s.`status`, s.`priority`, s.`assignee_id`, s.`source_session_id`, NULL, s.`version`, CONVERT_TZ(s.`created_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.`updated_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.solved_at, @main_source_utc_offset, '+00:00'), NULL, s.`category_snapshot`, s.`asset_check_status`, s.`impact_scope`, s.`urgency_level`, s.`auto_accepted`, s.`reopen_count`, s.`idempotency_key`, CONVERT_TZ(s.`first_response_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.`solved_at`, @main_source_utc_offset, '+00:00'), s.`rating_score`, s.`rating_comment`, CONVERT_TZ(s.`rated_at`, @main_source_utc_offset, '+00:00')
FROM `ticket` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'ticket','ticket',(SELECT COUNT(*) FROM `ticket`),(SELECT COUNT(*) FROM `v2_stage_ticket`);
INSERT INTO `v2_stage_ticket_transition` (`transition_id`,`ticket_id`,`from_status`,`to_status`,`event_code`,`operator_id`,`reason`,`occurred_at`)
SELECT s.`transition_id`, s.`ticket_id`, s.`from_status`, s.`to_status`, CONCAT('LEGACY_',UPPER(s.event)), s.`operator_id`, s.`reason`, CONVERT_TZ(s.`occurred_at`, @main_source_utc_offset, '+00:00')
FROM `ticket_transition` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'ticket_transition','ticket_transition',(SELECT COUNT(*) FROM `ticket_transition`),(SELECT COUNT(*) FROM `v2_stage_ticket_transition`);
INSERT INTO `v2_stage_exception_queue` (`exception_id`,`object_type`,`object_id`,`reason_code`,`status`,`claimed_by`,`claimed_at`,`resolved_by`,`resolved_at`,`reason`,`created_at`,`updated_at`,`title`,`detail`,`priority`)
SELECT s.`exception_id`, s.biz_type, s.biz_id, s.exception_type, s.`status`, NULL, NULL, s.`resolved_by`, CONVERT_TZ(s.`resolved_at`, @main_source_utc_offset, '+00:00'), s.resolution, CONVERT_TZ(s.`created_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.`updated_at`, @main_source_utc_offset, '+00:00'), s.`title`, s.`detail`, s.`priority`
FROM `exception_queue` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'exception_queue','exception_queue',(SELECT COUNT(*) FROM `exception_queue`),(SELECT COUNT(*) FROM `v2_stage_exception_queue`);
INSERT INTO `v2_stage_user_account` (`user_id`,`employee_no`,`display_name`,`department_id`,`identity_source`,`enabled`,`last_identity_sync_at`,`version`,`created_at`,`updated_at`,`password_hash`)
SELECT s.`user_id`, s.`employee_no`, s.name, s.`department_id`, s.`identity_source`, s.status='ACTIVE', NULL, 0, CONVERT_TZ(s.`created_at`, @main_source_utc_offset, '+00:00'), CONVERT_TZ(s.`updated_at`, @main_source_utc_offset, '+00:00'), s.`password_hash`
FROM `user` s;
INSERT INTO migration_v2_counts (source_table,target_table,source_rows,staged_rows) SELECT 'user','user_account',(SELECT COUNT(*) FROM `user`),(SELECT COUNT(*) FROM `v2_stage_user_account`);
INSERT INTO v2_stage_engineer_runtime_state (engineer_id,presence,version,created_at,updated_at) SELECT DISTINCT user_id,'OFFLINE',0,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6) FROM v2_stage_user_role WHERE role_code='ENGINEER' AND revoked_at IS NULL;
INSERT INTO v2_stage_service_calendar (calendar_id,timezone,work_week_json,work_intervals_json,lunch_pauses,version,effective_from,created_at,updated_at) VALUES ('DEFAULT','Asia/Shanghai','[1,2,3,4,5]','[{"start":"09:00","end":"12:00"},{"start":"13:00","end":"18:00"}]',1,1,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6),UTC_TIMESTAMP(6));
INSERT INTO schema_migration_audit (version,checksum,operator_id,source_timezone,started_at,completed_at) VALUES ('V2_0','9c042dae9b9e2e8eab45a4281dad6dd8166c0af9a50917330a718b4f4b0c7e43',@migration_operator,@main_source_utc_offset,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6));
 COMMIT;
END$$
DELIMITER ;
CALL migration_v2_copy();
DROP PROCEDURE migration_v2_copy;
DO RELEASE_LOCK(CONCAT(DATABASE(),'.schema_v2'));
