-- Generated by db/tools/build_migration.py; reviewed main 388f51d only.
-- Execute with a fail-fast versioned runner; never mysql --force. See db/README.md.
USE it_ticket_system;
SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET SESSION sql_mode = 'STRICT_ALL_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- Keep the same application maintenance/read-only window through this entire file.
DELIMITER $$
CREATE PROCEDURE migration_v2_cutover_guard()
BEGIN
 IF COALESCE(GET_LOCK(CONCAT(DATABASE(),'.schema_v2'),0),0)<>1 THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Another schema migration owns the advisory lock';
 END IF;
 IF COALESCE(@main_writes_stopped,0)<>1 OR COALESCE(@migration_operator,'')='' THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Require stopped writers and named migration operator';
 END IF;
 IF NOT EXISTS (SELECT 1 FROM schema_migration_audit WHERE version='V2_0') OR EXISTS (SELECT 1 FROM schema_migration_audit WHERE version='V2_1') THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Require completed V2_0 and unapplied V2_1';
 END IF;
 IF EXISTS (SELECT 1 FROM migration_v2_issue) OR EXISTS (SELECT 1 FROM migration_v2_counts WHERE source_rows<>staged_rows) THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unresolved migration issues or row-count mismatch';
 END IF;
 IF (SELECT COUNT(*) FROM `user_role`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='user_role') OR (SELECT COUNT(*) FROM `v2_stage_user_role`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='user_role') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: user_role'; END IF;
 IF (SELECT COUNT(*) FROM `support_team`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='support_team') OR (SELECT COUNT(*) FROM `v2_stage_support_team`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='support_team') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: support_team'; END IF;
 IF (SELECT COUNT(*) FROM `team_member`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='team_member') OR (SELECT COUNT(*) FROM `v2_stage_team_member`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='team_member') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: team_member'; END IF;
 IF (SELECT COUNT(*) FROM `category`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='category') OR (SELECT COUNT(*) FROM `v2_stage_category`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='category') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: category'; END IF;
 IF (SELECT COUNT(*) FROM `category_route`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='category_route') OR (SELECT COUNT(*) FROM `v2_stage_category_route`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='category_route') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: category_route'; END IF;
 IF (SELECT COUNT(*) FROM `consultation`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='consultation') OR (SELECT COUNT(*) FROM `v2_stage_consultation`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='consultation') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: consultation'; END IF;
 IF (SELECT COUNT(*) FROM `consultation_message`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='consultation_message') OR (SELECT COUNT(*) FROM `v2_stage_consultation_message`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='consultation_message') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: consultation_message'; END IF;
 IF (SELECT COUNT(*) FROM `ticket_draft`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='ticket_draft') OR (SELECT COUNT(*) FROM `v2_stage_ticket_draft`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='ticket_draft') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: ticket_draft'; END IF;
 IF (SELECT COUNT(*) FROM `assignment`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='assignment') OR (SELECT COUNT(*) FROM `v2_stage_assignment`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='assignment') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: assignment'; END IF;
 IF (SELECT COUNT(*) FROM `sla_instance`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='sla_instance') OR (SELECT COUNT(*) FROM `v2_stage_sla_instance`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='sla_instance') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: sla_instance'; END IF;
 IF (SELECT COUNT(*) FROM `sla_pause`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='sla_pause') OR (SELECT COUNT(*) FROM `v2_stage_sla_pause`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='sla_pause') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: sla_pause'; END IF;
 IF (SELECT COUNT(*) FROM `notification`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='notification') OR (SELECT COUNT(*) FROM `v2_stage_notification`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='notification') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: notification'; END IF;
 IF (SELECT COUNT(*) FROM `audit_log`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='audit_log') OR (SELECT COUNT(*) FROM `v2_stage_audit_log`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='audit_log') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: audit_log'; END IF;
 IF (SELECT COUNT(*) FROM `knowledge_article`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='knowledge_article') OR (SELECT COUNT(*) FROM `v2_stage_knowledge_article`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='knowledge_article') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: knowledge_article'; END IF;
 IF (SELECT COUNT(*) FROM `knowledge_version`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='knowledge_version') OR (SELECT COUNT(*) FROM `v2_stage_knowledge_version`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='knowledge_version') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: knowledge_version'; END IF;
 IF (SELECT COUNT(*) FROM `ai_interaction`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='ai_interaction') OR (SELECT COUNT(*) FROM `v2_stage_ai_interaction`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='ai_interaction') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: ai_interaction'; END IF;
 IF (SELECT COUNT(*) FROM `ticket`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='ticket') OR (SELECT COUNT(*) FROM `v2_stage_ticket`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='ticket') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: ticket'; END IF;
 IF (SELECT COUNT(*) FROM `ticket_transition`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='ticket_transition') OR (SELECT COUNT(*) FROM `v2_stage_ticket_transition`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='ticket_transition') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: ticket_transition'; END IF;
 IF (SELECT COUNT(*) FROM `exception_queue`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='exception_queue') OR (SELECT COUNT(*) FROM `v2_stage_exception_queue`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='exception_queue') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: exception_queue'; END IF;
 IF (SELECT COUNT(*) FROM `user`)<>(SELECT source_rows FROM migration_v2_counts WHERE source_table='user') OR (SELECT COUNT(*) FROM `v2_stage_user_account`)<>(SELECT staged_rows FROM migration_v2_counts WHERE source_table='user') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Row-count drift: user'; END IF;
 IF NOT EXISTS (SELECT 1 FROM schema_migration_audit WHERE version='V2_0' AND checksum='9c042dae9b9e2e8eab45a4281dad6dd8166c0af9a50917330a718b4f4b0c7e43') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Staged schema checksum differs from cutover version'; END IF;
END$$
DELIMITER ;
CALL migration_v2_cutover_guard();
DROP PROCEDURE migration_v2_cutover_guard;

-- One atomic metadata switch. Changed source tables remain available; deferred tables stay untouched.
RENAME TABLE
 `user_role` TO `legacy_v1_user_role`,
 `support_team` TO `legacy_v1_support_team`,
 `team_member` TO `legacy_v1_team_member`,
 `category` TO `legacy_v1_category`,
 `category_route` TO `legacy_v1_category_route`,
 `consultation` TO `legacy_v1_consultation`,
 `consultation_message` TO `legacy_v1_consultation_message`,
 `ticket_draft` TO `legacy_v1_ticket_draft`,
 `assignment` TO `legacy_v1_assignment`,
 `sla_instance` TO `legacy_v1_sla_instance`,
 `sla_pause` TO `legacy_v1_sla_pause`,
 `notification` TO `legacy_v1_notification`,
 `audit_log` TO `legacy_v1_audit_log`,
 `knowledge_article` TO `legacy_v1_knowledge_article`,
 `knowledge_version` TO `legacy_v1_knowledge_version`,
 `ai_interaction` TO `legacy_v1_ai_interaction`,
 `ticket` TO `legacy_v1_ticket`,
 `ticket_transition` TO `legacy_v1_ticket_transition`,
 `exception_queue` TO `legacy_v1_exception_queue`,
 `user` TO `legacy_v1_user`,
 `v2_stage_user_account` TO `user_account`,
 `v2_stage_user_role` TO `user_role`,
 `v2_stage_support_team` TO `support_team`,
 `v2_stage_team_member` TO `team_member`,
 `v2_stage_engineer_runtime_state` TO `engineer_runtime_state`,
 `v2_stage_engineer_category_capability` TO `engineer_category_capability`,
 `v2_stage_category` TO `category`,
 `v2_stage_category_route` TO `category_route`,
 `v2_stage_consultation` TO `consultation`,
 `v2_stage_consultation_message` TO `consultation_message`,
 `v2_stage_ticket_draft` TO `ticket_draft`,
 `v2_stage_assignment` TO `assignment`,
 `v2_stage_sla_instance` TO `sla_instance`,
 `v2_stage_sla_pause` TO `sla_pause`,
 `v2_stage_notification` TO `notification`,
 `v2_stage_audit_log` TO `audit_log`,
 `v2_stage_idempotency_record` TO `idempotency_record`,
 `v2_stage_outbox_event` TO `outbox_event`,
 `v2_stage_knowledge_article` TO `knowledge_article`,
 `v2_stage_knowledge_version` TO `knowledge_version`,
 `v2_stage_ai_interaction` TO `ai_interaction`,
 `v2_stage_ticket` TO `ticket`,
 `v2_stage_ticket_transition` TO `ticket_transition`,
 `v2_stage_service_calendar` TO `service_calendar`,
 `v2_stage_calendar_holiday` TO `calendar_holiday`,
 `v2_stage_exception_queue` TO `exception_queue`;
INSERT INTO schema_migration_audit (version,checksum,operator_id,source_timezone,started_at,completed_at) SELECT 'V2_1','9c042dae9b9e2e8eab45a4281dad6dd8166c0af9a50917330a718b4f4b0c7e43',@migration_operator,source_timezone,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6) FROM schema_migration_audit WHERE version='V2_0';
DO RELEASE_LOCK(CONCAT(DATABASE(),'.schema_v2'));
