-- Generated by db/tools/build_latest_migration.py; 470ce57 -> PRD 2.2 unified fields (a99ab6a plus approved PRD alignment).
-- Run after V2_1 for 388f51d, or against the frozen 470ce57 baseline.
-- Stop writers throughout. Fail fast; never mysql --force. See db/README.md.
USE it_ticket_system;
SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET SESSION sql_mode = 'STRICT_ALL_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE TABLE IF NOT EXISTS schema_migration_audit (
 version VARCHAR(32) PRIMARY KEY, checksum CHAR(64) NOT NULL,
 operator_id VARCHAR(128) NOT NULL, source_timezone VARCHAR(64) NOT NULL,
 started_at DATETIME(6) NOT NULL, completed_at DATETIME(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DELIMITER $$
CREATE PROCEDURE migration_v2_2_guard()
BEGIN
 IF COALESCE(GET_LOCK(CONCAT(DATABASE(),'.schema_v2'),0),0)<>1 THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Another schema migration owns the advisory lock';
 END IF;
 IF COALESCE(@main_writes_stopped,0)<>1 OR COALESCE(@migration_operator,'')='' THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Require stopped writers and named migration operator';
 END IF;
 IF EXISTS (SELECT 1 FROM schema_migration_audit WHERE version='V2_2') THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V2_2 already applied; do not replay';
 END IF;
 IF COALESCE(@canonical_source_revision,'')<>'470ce57' THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Verify frozen 470ce57 source schema and set canonical_source_revision';
 END IF;
 IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='user') THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Target user table already exists; inspect source revision';
 END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='user_account' AND column_name='user_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column user_account.user_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='user_account' AND column_name='employee_no') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column user_account.employee_no'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='user_account' AND column_name='display_name') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column user_account.display_name'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='user_account' AND column_name='department_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column user_account.department_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='user_account' AND column_name='identity_source') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column user_account.identity_source'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='user_account' AND column_name='enabled') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column user_account.enabled'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='user_account' AND column_name='last_identity_sync_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column user_account.last_identity_sync_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='user_account' AND column_name='version') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column user_account.version'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='user_account' AND column_name='created_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column user_account.created_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='user_account' AND column_name='updated_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column user_account.updated_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='user_account' AND column_name='password_hash') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column user_account.password_hash'; END IF;
 IF (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='user_account')<>11 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unexpected source columns: user_account'; END IF;
 IF EXISTS (SELECT 1 FROM `user_account` WHERE enabled IS NULL OR enabled NOT IN (0,1)) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unknown enabled value: user_account; explicit mapping required'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='support_team' AND column_name='team_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column support_team.team_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='support_team' AND column_name='name') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column support_team.name'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='support_team' AND column_name='enabled') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column support_team.enabled'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='support_team' AND column_name='version') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column support_team.version'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='support_team' AND column_name='created_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column support_team.created_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='support_team' AND column_name='updated_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column support_team.updated_at'; END IF;
 IF (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='support_team')<>6 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unexpected source columns: support_team'; END IF;
 IF EXISTS (SELECT 1 FROM `support_team` WHERE enabled IS NULL OR enabled NOT IN (0,1)) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unknown enabled value: support_team; explicit mapping required'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='team_member' AND column_name='team_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column team_member.team_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='team_member' AND column_name='engineer_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column team_member.engineer_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='team_member' AND column_name='joined_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column team_member.joined_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='team_member' AND column_name='left_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column team_member.left_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='team_member' AND column_name='enabled') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column team_member.enabled'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='team_member' AND column_name='created_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column team_member.created_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='team_member' AND column_name='updated_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column team_member.updated_at'; END IF;
 IF (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='team_member')<>7 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unexpected source columns: team_member'; END IF;
 IF EXISTS (SELECT 1 FROM `team_member` WHERE enabled IS NULL OR enabled NOT IN (0,1)) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unknown enabled value: team_member; explicit mapping required'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='category' AND column_name='category_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column category.category_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='category' AND column_name='parent_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column category.parent_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='category' AND column_name='nature') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column category.nature'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='category' AND column_name='name') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column category.name'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='category' AND column_name='level') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column category.level'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='category' AND column_name='definition_version') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column category.definition_version'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='category' AND column_name='enabled') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column category.enabled'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='category' AND column_name='version') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column category.version'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='category' AND column_name='created_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column category.created_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='category' AND column_name='updated_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column category.updated_at'; END IF;
 IF (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='category')<>10 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unexpected source columns: category'; END IF;
 IF EXISTS (SELECT 1 FROM `category` WHERE enabled IS NULL OR enabled NOT IN (0,1)) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unknown enabled value: category; explicit mapping required'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='ticket_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.ticket_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='creator_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.creator_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='ticket_nature') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.ticket_nature'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='category_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.category_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='title') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.title'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='description') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.description'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='impact_description') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.impact_description'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='urgency_description') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.urgency_description'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='location') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.location'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='contact') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.contact'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='asset_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.asset_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='status') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.status'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='priority') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.priority'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='assignee_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.assignee_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='source_session_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.source_session_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='field_snapshot_json') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.field_snapshot_json'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='version') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.version'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='created_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.created_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='updated_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.updated_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='completed_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.completed_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='closed_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.closed_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='category_snapshot') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.category_snapshot'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='asset_check_status') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.asset_check_status'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='impact_scope') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.impact_scope'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='urgency_level') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.urgency_level'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='auto_accepted') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.auto_accepted'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='reopen_count') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.reopen_count'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='idempotency_key') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.idempotency_key'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='first_response_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.first_response_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='solved_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.solved_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='rating_score') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.rating_score'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='rating_comment') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.rating_comment'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket' AND column_name='rated_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket.rated_at'; END IF;
 IF (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket')<>33 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unexpected source columns: ticket'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_draft' AND column_name='draft_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_draft.draft_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_draft' AND column_name='creator_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_draft.creator_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_draft' AND column_name='nature') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_draft.nature'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_draft' AND column_name='category_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_draft.category_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_draft' AND column_name='payload_json') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_draft.payload_json'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_draft' AND column_name='last_saved_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_draft.last_saved_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_draft' AND column_name='expires_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_draft.expires_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_draft' AND column_name='version') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_draft.version'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_draft' AND column_name='created_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_draft.created_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_draft' AND column_name='updated_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_draft.updated_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_draft' AND column_name='title') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_draft.title'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_draft' AND column_name='description') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_draft.description'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_draft' AND column_name='impact_description') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_draft.impact_description'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_draft' AND column_name='urgency_description') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_draft.urgency_description'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_draft' AND column_name='location') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_draft.location'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_draft' AND column_name='contact') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_draft.contact'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_draft' AND column_name='asset_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_draft.asset_id'; END IF;
 IF (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_draft')<>17 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unexpected source columns: ticket_draft'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='consultation' AND column_name='session_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column consultation.session_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='consultation' AND column_name='creator_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column consultation.creator_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='consultation' AND column_name='category_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column consultation.category_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='consultation' AND column_name='status') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column consultation.status'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='consultation' AND column_name='current_engineer_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column consultation.current_engineer_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='consultation' AND column_name='source') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column consultation.source'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='consultation' AND column_name='resolution_type') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column consultation.resolution_type'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='consultation' AND column_name='converted_ticket_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column consultation.converted_ticket_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='consultation' AND column_name='closed_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column consultation.closed_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='consultation' AND column_name='version') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column consultation.version'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='consultation' AND column_name='created_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column consultation.created_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='consultation' AND column_name='updated_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column consultation.updated_at'; END IF;
 IF (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='consultation')<>12 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unexpected source columns: consultation'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_transition' AND column_name='transition_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_transition.transition_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_transition' AND column_name='ticket_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_transition.ticket_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_transition' AND column_name='from_status') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_transition.from_status'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_transition' AND column_name='to_status') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_transition.to_status'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_transition' AND column_name='event_code') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_transition.event_code'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_transition' AND column_name='operator_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_transition.operator_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_transition' AND column_name='reason') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_transition.reason'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_transition' AND column_name='occurred_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ticket_transition.occurred_at'; END IF;
 IF (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ticket_transition')<>8 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unexpected source columns: ticket_transition'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance' AND column_name='sla_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column sla_instance.sla_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance' AND column_name='biz_type') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column sla_instance.biz_type'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance' AND column_name='biz_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column sla_instance.biz_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance' AND column_name='sla_type') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column sla_instance.sla_type'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance' AND column_name='status') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column sla_instance.status'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance' AND column_name='target_work_seconds') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column sla_instance.target_work_seconds'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance' AND column_name='elapsed_work_seconds') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column sla_instance.elapsed_work_seconds'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance' AND column_name='paused_seconds') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column sla_instance.paused_seconds'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance' AND column_name='target_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column sla_instance.target_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance' AND column_name='breached_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column sla_instance.breached_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance' AND column_name='met_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column sla_instance.met_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance' AND column_name='calendar_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column sla_instance.calendar_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance' AND column_name='calendar_version') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column sla_instance.calendar_version'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance' AND column_name='version') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column sla_instance.version'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance' AND column_name='created_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column sla_instance.created_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance' AND column_name='updated_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column sla_instance.updated_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance' AND column_name='priority_snapshot') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column sla_instance.priority_snapshot'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance' AND column_name='near_breach_notified') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column sla_instance.near_breach_notified'; END IF;
 IF (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sla_instance')<>18 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unexpected source columns: sla_instance'; END IF;
 IF EXISTS (SELECT 1 FROM sla_instance WHERE biz_type NOT IN ('TICKET','CONSULTATION') OR (biz_type='TICKET' AND CHAR_LENGTH(biz_id)>32)) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Invalid SLA business association'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='knowledge_version' AND column_name='version_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column knowledge_version.version_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='knowledge_version' AND column_name='article_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column knowledge_version.article_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='knowledge_version' AND column_name='version_no') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column knowledge_version.version_no'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='knowledge_version' AND column_name='content_json') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column knowledge_version.content_json'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='knowledge_version' AND column_name='author_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column knowledge_version.author_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='knowledge_version' AND column_name='reviewer_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column knowledge_version.reviewer_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='knowledge_version' AND column_name='published_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column knowledge_version.published_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='knowledge_version' AND column_name='change_note') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column knowledge_version.change_note'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='knowledge_version' AND column_name='platform_reviewer_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column knowledge_version.platform_reviewer_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='knowledge_version' AND column_name='platform_reviewed_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column knowledge_version.platform_reviewed_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='knowledge_version' AND column_name='platform_review_decision') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column knowledge_version.platform_review_decision'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='knowledge_version' AND column_name='created_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column knowledge_version.created_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='knowledge_version' AND column_name='updated_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column knowledge_version.updated_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='knowledge_version' AND column_name='search_text') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column knowledge_version.search_text'; END IF;
 IF (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='knowledge_version')<>14 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unexpected source columns: knowledge_version'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ai_interaction' AND column_name='interaction_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ai_interaction.interaction_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ai_interaction' AND column_name='session_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ai_interaction.session_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ai_interaction' AND column_name='model_version') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ai_interaction.model_version'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ai_interaction' AND column_name='retrieved_versions_json') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ai_interaction.retrieved_versions_json'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ai_interaction' AND column_name='confidence') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ai_interaction.confidence'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ai_interaction' AND column_name='feedback') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ai_interaction.feedback'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ai_interaction' AND column_name='latency_ms') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ai_interaction.latency_ms'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ai_interaction' AND column_name='occurred_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ai_interaction.occurred_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ai_interaction' AND column_name='created_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ai_interaction.created_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ai_interaction' AND column_name='updated_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column ai_interaction.updated_at'; END IF;
 IF (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='ai_interaction')<>10 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unexpected source columns: ai_interaction'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='audit_log' AND column_name='audit_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column audit_log.audit_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='audit_log' AND column_name='actor_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column audit_log.actor_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='audit_log' AND column_name='action') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column audit_log.action'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='audit_log' AND column_name='object_type') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column audit_log.object_type'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='audit_log' AND column_name='object_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column audit_log.object_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='audit_log' AND column_name='before_json') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column audit_log.before_json'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='audit_log' AND column_name='after_json') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column audit_log.after_json'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='audit_log' AND column_name='reason') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column audit_log.reason'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='audit_log' AND column_name='request_id') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column audit_log.request_id'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='audit_log' AND column_name='occurred_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column audit_log.occurred_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='audit_log' AND column_name='created_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column audit_log.created_at'; END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='audit_log' AND column_name='updated_at') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column audit_log.updated_at'; END IF;
 IF (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='audit_log')<>12 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unexpected source columns: audit_log'; END IF;
END$$
DELIMITER ;
CALL migration_v2_2_guard();
DROP PROCEDURE migration_v2_2_guard;

CREATE TABLE `v2_2_stage_user` (
 user_id VARCHAR(64) PRIMARY KEY, employee_no VARCHAR(64) NOT NULL,
 name VARCHAR(255) NOT NULL, department_id VARCHAR(64) NOT NULL,
 status VARCHAR(32) NOT NULL, identity_source VARCHAR(64) NOT NULL,
 last_identity_sync_at DATETIME(6), version BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_user_employee_no(employee_no), KEY idx_user_department(department_id),
 KEY idx_user_status(status),
  password_hash VARCHAR(100) COMMENT 'Compatibility: local BCrypt authentication; remove after SSO rollout'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `v2_2_stage_support_team` (
 team_id VARCHAR(64) PRIMARY KEY, name VARCHAR(255) NOT NULL, status VARCHAR(32) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, UNIQUE KEY uk_team_name(name), KEY idx_team_status(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `v2_2_stage_team_member` (
 team_id VARCHAR(64) NOT NULL, engineer_id VARCHAR(64) NOT NULL,
 joined_at DATETIME(6) NOT NULL, left_at DATETIME(6), status VARCHAR(32) NOT NULL,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY(team_id,engineer_id), KEY idx_member_engineer(engineer_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `v2_2_stage_category` (
 category_id VARCHAR(64) PRIMARY KEY, parent_id VARCHAR(64),
 ticket_nature VARCHAR(32) NOT NULL, name VARCHAR(255) NOT NULL, level SMALLINT NOT NULL,
 definition_version VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, KEY idx_category_parent(parent_id,level,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `v2_2_stage_ticket` (
  ticket_id VARCHAR(32) PRIMARY KEY, creator_id VARCHAR(64) NOT NULL,
  nature VARCHAR(32) NOT NULL, category_id VARCHAR(64) NOT NULL,
  title VARCHAR(100) NOT NULL, description TEXT NOT NULL,
  impact_description TEXT NOT NULL, urgency_description TEXT NOT NULL,
  location VARCHAR(255), contact VARCHAR(255), asset_id VARCHAR(64),
  status VARCHAR(32) NOT NULL, priority VARCHAR(32) NOT NULL,
  assignee_id VARCHAR(64), source_session_id VARCHAR(32),
  field_definition_snapshot JSON, version BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
  completed_at DATETIME(6), closed_at DATETIME(6),
  KEY idx_ticket_creator_status (creator_id,status),
  KEY idx_ticket_assignee_status (assignee_id,status),
  KEY idx_ticket_priority_status (priority,status),
  category_snapshot VARCHAR(500),
 asset_check_status VARCHAR(32),
 impact_scope VARCHAR(32),
 urgency_level VARCHAR(32),
 auto_accepted TINYINT(1) NOT NULL DEFAULT 0,
 reopen_count INT NOT NULL DEFAULT 0,
 idempotency_key VARCHAR(128),
 first_response_at DATETIME(6),
 solved_at DATETIME(6),
 rating_score INT,
 rating_comment VARCHAR(2000),
 rated_at DATETIME(6),
 KEY idx_ticket_title_category(title,category_id,created_at),
 KEY idx_ticket_source_session(source_session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `v2_2_stage_ticket_draft` (
  draft_id VARCHAR(64) PRIMARY KEY, creator_id VARCHAR(64) NOT NULL,
  ticket_nature VARCHAR(32), category_id VARCHAR(64), payload_json JSON NOT NULL,
 last_saved_at DATETIME(6) NOT NULL, expires_at DATETIME(6) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, UNIQUE KEY uk_active_draft(creator_id),
  title VARCHAR(100),
 description TEXT,
 impact_description TEXT,
 urgency_description TEXT,
 location VARCHAR(255),
 contact VARCHAR(255),
 asset_id VARCHAR(64)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `v2_2_stage_consultation` (
 session_id VARCHAR(32) PRIMARY KEY, creator_id VARCHAR(64) NOT NULL,
 category_id VARCHAR(64), status VARCHAR(32) NOT NULL, current_engineer_id VARCHAR(64),
 source VARCHAR(32) NOT NULL, resolved_type VARCHAR(32), converted_ticket_id VARCHAR(32),
 closed_at DATETIME(6), version BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 KEY idx_consult_creator(creator_id,status,created_at),
 KEY idx_consult_engineer(current_engineer_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `v2_2_stage_ticket_transition` (
  transition_id VARCHAR(64) PRIMARY KEY, ticket_id VARCHAR(32) NOT NULL,
  from_status VARCHAR(32), to_status VARCHAR(32) NOT NULL,
  event VARCHAR(64) NOT NULL, operator_id VARCHAR(64) NOT NULL,
  reason TEXT, occurred_at DATETIME(6) NOT NULL,
  UNIQUE KEY uk_transition_order (ticket_id,occurred_at,transition_id),
  KEY idx_transition_ticket (ticket_id,occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `v2_2_stage_sla_instance` (
 sla_id VARCHAR(64) PRIMARY KEY, ticket_id VARCHAR(32), biz_type VARCHAR(32) NOT NULL,
 biz_id VARCHAR(64) NOT NULL, sla_type VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL,
 target_work_seconds BIGINT NOT NULL, elapsed_work_seconds BIGINT NOT NULL DEFAULT 0,
 paused_seconds BIGINT NOT NULL DEFAULT 0, target_at DATETIME(6),
 breach_at DATETIME(6), met_at DATETIME(6), calendar_id VARCHAR(64) NOT NULL,
 calendar_version BIGINT NOT NULL, version BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_sla_business(biz_type,biz_id,sla_type),
 KEY idx_sla_due(status,target_at),
 KEY idx_sla_ticket(ticket_id),
  priority_snapshot VARCHAR(32),
 near_breach_notified TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `v2_2_stage_knowledge_version` (
 version_id VARCHAR(64) PRIMARY KEY, article_id VARCHAR(64) NOT NULL,
 version_no INT NOT NULL, content JSON NOT NULL, author_id VARCHAR(64) NOT NULL,
 reviewer_id VARCHAR(64), published_at DATETIME(6), change_note VARCHAR(2000),
 platform_reviewer_id VARCHAR(64), platform_reviewed_at DATETIME(6),
 platform_review_decision VARCHAR(32),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_knowledge_version(article_id,version_no),
  search_text TEXT GENERATED ALWAYS AS (CONCAT_WS(' ', JSON_UNQUOTE(JSON_EXTRACT(content, '$.title')), JSON_UNQUOTE(JSON_EXTRACT(content, '$.summary')), JSON_UNQUOTE(JSON_EXTRACT(content, '$.keywords')), JSON_UNQUOTE(JSON_EXTRACT(content, '$.body')))) STORED,
 FULLTEXT KEY ft_knowledge_search(search_text) WITH PARSER ngram
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `v2_2_stage_ai_interaction` (
 interaction_id VARCHAR(64) PRIMARY KEY, session_id VARCHAR(32) NOT NULL,
 model_version VARCHAR(128) NOT NULL, retrieved_versions JSON NOT NULL,
 confidence DECIMAL(8,4), feedback VARCHAR(32), latency BIGINT NOT NULL,
 occurred_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, KEY idx_ai_session(session_id,occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `v2_2_stage_audit_log` (
 audit_id VARCHAR(64) PRIMARY KEY, actor_id VARCHAR(64), action VARCHAR(128) NOT NULL,
 object_type VARCHAR(64) NOT NULL, object_id VARCHAR(64) NOT NULL,
 before_value JSON, after_value JSON, reason VARCHAR(2000), request_id VARCHAR(128) NOT NULL,
 occurred_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 KEY idx_audit_object(object_type,object_id,occurred_at),
 KEY idx_audit_actor(actor_id,occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELIMITER $$
CREATE PROCEDURE migration_v2_2_copy()
BEGIN
 DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
 START TRANSACTION;
 INSERT INTO `v2_2_stage_user` (`user_id`,`employee_no`,`name`,`department_id`,`status`,`identity_source`,`last_identity_sync_at`,`version`,`created_at`,`updated_at`,`password_hash`) SELECT `user_id`,`employee_no`,`display_name`,`department_id`,CASE enabled WHEN 1 THEN 'ACTIVE' WHEN 0 THEN 'DISABLED' END,`identity_source`,`last_identity_sync_at`,`version`,`created_at`,`updated_at`,`password_hash` FROM `user_account`;
 IF (SELECT COUNT(*) FROM `user_account`)<>(SELECT COUNT(*) FROM `v2_2_stage_user`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V2_2 row-count mismatch: user_account'; END IF;
 INSERT INTO `v2_2_stage_support_team` (`team_id`,`name`,`status`,`version`,`created_at`,`updated_at`) SELECT `team_id`,`name`,CASE enabled WHEN 1 THEN 'ACTIVE' WHEN 0 THEN 'DISABLED' END,`version`,`created_at`,`updated_at` FROM `support_team`;
 IF (SELECT COUNT(*) FROM `support_team`)<>(SELECT COUNT(*) FROM `v2_2_stage_support_team`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V2_2 row-count mismatch: support_team'; END IF;
 INSERT INTO `v2_2_stage_team_member` (`team_id`,`engineer_id`,`joined_at`,`left_at`,`status`,`created_at`,`updated_at`) SELECT `team_id`,`engineer_id`,`joined_at`,`left_at`,CASE enabled WHEN 1 THEN 'ACTIVE' WHEN 0 THEN 'DISABLED' END,`created_at`,`updated_at` FROM `team_member`;
 IF (SELECT COUNT(*) FROM `team_member`)<>(SELECT COUNT(*) FROM `v2_2_stage_team_member`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V2_2 row-count mismatch: team_member'; END IF;
 INSERT INTO `v2_2_stage_category` (`category_id`,`parent_id`,`ticket_nature`,`name`,`level`,`definition_version`,`status`,`version`,`created_at`,`updated_at`) SELECT `category_id`,`parent_id`,`nature`,`name`,`level`,`definition_version`,CASE enabled WHEN 1 THEN 'ACTIVE' WHEN 0 THEN 'DISABLED' END,`version`,`created_at`,`updated_at` FROM `category`;
 IF (SELECT COUNT(*) FROM `category`)<>(SELECT COUNT(*) FROM `v2_2_stage_category`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V2_2 row-count mismatch: category'; END IF;
 INSERT INTO `v2_2_stage_ticket` (`ticket_id`,`creator_id`,`nature`,`category_id`,`title`,`description`,`impact_description`,`urgency_description`,`location`,`contact`,`asset_id`,`status`,`priority`,`assignee_id`,`source_session_id`,`field_definition_snapshot`,`version`,`created_at`,`updated_at`,`completed_at`,`closed_at`,`category_snapshot`,`asset_check_status`,`impact_scope`,`urgency_level`,`auto_accepted`,`reopen_count`,`idempotency_key`,`first_response_at`,`solved_at`,`rating_score`,`rating_comment`,`rated_at`) SELECT `ticket_id`,`creator_id`,`ticket_nature`,`category_id`,`title`,`description`,`impact_description`,`urgency_description`,`location`,`contact`,`asset_id`,`status`,`priority`,`assignee_id`,`source_session_id`,`field_snapshot_json`,`version`,`created_at`,`updated_at`,`completed_at`,`closed_at`,`category_snapshot`,`asset_check_status`,`impact_scope`,`urgency_level`,`auto_accepted`,`reopen_count`,`idempotency_key`,`first_response_at`,`solved_at`,`rating_score`,`rating_comment`,`rated_at` FROM `ticket`;
 IF (SELECT COUNT(*) FROM `ticket`)<>(SELECT COUNT(*) FROM `v2_2_stage_ticket`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V2_2 row-count mismatch: ticket'; END IF;
 INSERT INTO `v2_2_stage_ticket_draft` (`draft_id`,`creator_id`,`ticket_nature`,`category_id`,`payload_json`,`last_saved_at`,`expires_at`,`version`,`created_at`,`updated_at`,`title`,`description`,`impact_description`,`urgency_description`,`location`,`contact`,`asset_id`) SELECT `draft_id`,`creator_id`,`nature`,`category_id`,`payload_json`,`last_saved_at`,`expires_at`,`version`,`created_at`,`updated_at`,`title`,`description`,`impact_description`,`urgency_description`,`location`,`contact`,`asset_id` FROM `ticket_draft`;
 IF (SELECT COUNT(*) FROM `ticket_draft`)<>(SELECT COUNT(*) FROM `v2_2_stage_ticket_draft`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V2_2 row-count mismatch: ticket_draft'; END IF;
 INSERT INTO `v2_2_stage_consultation` (`session_id`,`creator_id`,`category_id`,`status`,`current_engineer_id`,`source`,`resolved_type`,`converted_ticket_id`,`closed_at`,`version`,`created_at`,`updated_at`) SELECT `session_id`,`creator_id`,`category_id`,`status`,`current_engineer_id`,`source`,`resolution_type`,`converted_ticket_id`,`closed_at`,`version`,`created_at`,`updated_at` FROM `consultation`;
 IF (SELECT COUNT(*) FROM `consultation`)<>(SELECT COUNT(*) FROM `v2_2_stage_consultation`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V2_2 row-count mismatch: consultation'; END IF;
 INSERT INTO `v2_2_stage_ticket_transition` (`transition_id`,`ticket_id`,`from_status`,`to_status`,`event`,`operator_id`,`reason`,`occurred_at`) SELECT `transition_id`,`ticket_id`,`from_status`,`to_status`,`event_code`,`operator_id`,`reason`,`occurred_at` FROM `ticket_transition`;
 IF (SELECT COUNT(*) FROM `ticket_transition`)<>(SELECT COUNT(*) FROM `v2_2_stage_ticket_transition`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V2_2 row-count mismatch: ticket_transition'; END IF;
 INSERT INTO `v2_2_stage_sla_instance` (`sla_id`,`ticket_id`,`biz_type`,`biz_id`,`sla_type`,`status`,`target_work_seconds`,`elapsed_work_seconds`,`paused_seconds`,`target_at`,`breach_at`,`met_at`,`calendar_id`,`calendar_version`,`version`,`created_at`,`updated_at`,`priority_snapshot`,`near_breach_notified`) SELECT `sla_id`,CASE WHEN biz_type='TICKET' THEN biz_id ELSE NULL END,`biz_type`,`biz_id`,`sla_type`,`status`,`target_work_seconds`,`elapsed_work_seconds`,`paused_seconds`,`target_at`,`breached_at`,`met_at`,`calendar_id`,`calendar_version`,`version`,`created_at`,`updated_at`,`priority_snapshot`,`near_breach_notified` FROM `sla_instance`;
 IF (SELECT COUNT(*) FROM `sla_instance`)<>(SELECT COUNT(*) FROM `v2_2_stage_sla_instance`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V2_2 row-count mismatch: sla_instance'; END IF;
 INSERT INTO `v2_2_stage_knowledge_version` (`version_id`,`article_id`,`version_no`,`content`,`author_id`,`reviewer_id`,`published_at`,`change_note`,`platform_reviewer_id`,`platform_reviewed_at`,`platform_review_decision`,`created_at`,`updated_at`) SELECT `version_id`,`article_id`,`version_no`,`content_json`,`author_id`,`reviewer_id`,`published_at`,`change_note`,`platform_reviewer_id`,`platform_reviewed_at`,`platform_review_decision`,`created_at`,`updated_at` FROM `knowledge_version`;
 IF (SELECT COUNT(*) FROM `knowledge_version`)<>(SELECT COUNT(*) FROM `v2_2_stage_knowledge_version`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V2_2 row-count mismatch: knowledge_version'; END IF;
 INSERT INTO `v2_2_stage_ai_interaction` (`interaction_id`,`session_id`,`model_version`,`retrieved_versions`,`confidence`,`feedback`,`latency`,`occurred_at`,`created_at`,`updated_at`) SELECT `interaction_id`,`session_id`,`model_version`,`retrieved_versions_json`,`confidence`,`feedback`,`latency_ms`,`occurred_at`,`created_at`,`updated_at` FROM `ai_interaction`;
 IF (SELECT COUNT(*) FROM `ai_interaction`)<>(SELECT COUNT(*) FROM `v2_2_stage_ai_interaction`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V2_2 row-count mismatch: ai_interaction'; END IF;
 INSERT INTO `v2_2_stage_audit_log` (`audit_id`,`actor_id`,`action`,`object_type`,`object_id`,`before_value`,`after_value`,`reason`,`request_id`,`occurred_at`,`created_at`,`updated_at`) SELECT `audit_id`,`actor_id`,`action`,`object_type`,`object_id`,`before_json`,`after_json`,`reason`,`request_id`,`occurred_at`,`created_at`,`updated_at` FROM `audit_log`;
 IF (SELECT COUNT(*) FROM `audit_log`)<>(SELECT COUNT(*) FROM `v2_2_stage_audit_log`) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V2_2 row-count mismatch: audit_log'; END IF;
 COMMIT;
END$$
DELIMITER ;
CALL migration_v2_2_copy();
DROP PROCEDURE migration_v2_2_copy;

RENAME TABLE
 `user_account` TO `legacy_v2_user_account`,
 `support_team` TO `legacy_v2_support_team`,
 `team_member` TO `legacy_v2_team_member`,
 `category` TO `legacy_v2_category`,
 `ticket` TO `legacy_v2_ticket`,
 `ticket_draft` TO `legacy_v2_ticket_draft`,
 `consultation` TO `legacy_v2_consultation`,
 `ticket_transition` TO `legacy_v2_ticket_transition`,
 `sla_instance` TO `legacy_v2_sla_instance`,
 `knowledge_version` TO `legacy_v2_knowledge_version`,
 `ai_interaction` TO `legacy_v2_ai_interaction`,
 `audit_log` TO `legacy_v2_audit_log`,
 `v2_2_stage_user` TO `user`,
 `v2_2_stage_support_team` TO `support_team`,
 `v2_2_stage_team_member` TO `team_member`,
 `v2_2_stage_category` TO `category`,
 `v2_2_stage_ticket` TO `ticket`,
 `v2_2_stage_ticket_draft` TO `ticket_draft`,
 `v2_2_stage_consultation` TO `consultation`,
 `v2_2_stage_ticket_transition` TO `ticket_transition`,
 `v2_2_stage_sla_instance` TO `sla_instance`,
 `v2_2_stage_knowledge_version` TO `knowledge_version`,
 `v2_2_stage_ai_interaction` TO `ai_interaction`,
 `v2_2_stage_audit_log` TO `audit_log`;
INSERT INTO schema_migration_audit (version,checksum,operator_id,source_timezone,started_at,completed_at) VALUES ('V2_2','90ecaa0ff03b02d40e5c6676cc0a97b99bc30f94cce75d19f4d8c25b0fc8478f',@migration_operator,'+00:00',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6));
DO RELEASE_LOCK(CONCAT(DATABASE(),'.schema_v2'));
