-- Generated by db/tools/build_schema.py from SQL-007 + SQL-010.
-- Fresh empty database only. Existing main installations use db/migration.
CREATE DATABASE IF NOT EXISTS it_ticket_system CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE it_ticket_system;
SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE user_account (
 user_id VARCHAR(64) PRIMARY KEY, employee_no VARCHAR(64) NOT NULL,
 display_name VARCHAR(255) NOT NULL, department_id VARCHAR(64) NOT NULL,
 identity_source VARCHAR(64) NOT NULL, enabled TINYINT(1) NOT NULL,
 last_identity_sync_at DATETIME(6), version BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_user_employee_no(employee_no), KEY idx_user_department(department_id),
 KEY idx_user_enabled(enabled),
  password_hash VARCHAR(100) COMMENT 'Compatibility: local BCrypt authentication; remove after SSO rollout'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE user_role (
 user_id VARCHAR(64) NOT NULL, role_code VARCHAR(32) NOT NULL,
 granted_by VARCHAR(64) NOT NULL, granted_at DATETIME(6) NOT NULL,
 revoked_at DATETIME(6), created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY(user_id,role_code), KEY idx_role_revoked(revoked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE support_team (
 team_id VARCHAR(64) PRIMARY KEY, name VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, UNIQUE KEY uk_team_name(name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE team_member (
 team_id VARCHAR(64) NOT NULL, engineer_id VARCHAR(64) NOT NULL,
 joined_at DATETIME(6) NOT NULL, left_at DATETIME(6), enabled TINYINT(1) NOT NULL,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY(team_id,engineer_id), KEY idx_member_engineer(engineer_id,enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE engineer_runtime_state (
 engineer_id VARCHAR(64) PRIMARY KEY, presence VARCHAR(32) NOT NULL,
 last_activity_at DATETIME(6), last_assigned_at DATETIME(6),
 version BIGINT NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, KEY idx_engineer_presence(presence,last_activity_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE engineer_category_capability (
 engineer_id VARCHAR(64) NOT NULL, category_id VARCHAR(64) NOT NULL,
 team_id VARCHAR(64) NOT NULL, enabled TINYINT(1) NOT NULL,
 effective_at DATETIME(6) NOT NULL, expired_at DATETIME(6),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY(engineer_id,category_id,team_id,effective_at),
 KEY idx_capability_route(category_id,team_id,enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE category (
 category_id VARCHAR(64) PRIMARY KEY, parent_id VARCHAR(64),
 nature VARCHAR(32) NOT NULL, name VARCHAR(255) NOT NULL, level SMALLINT NOT NULL,
 definition_version VARCHAR(64) NOT NULL, enabled TINYINT(1) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, KEY idx_category_parent(parent_id,level,enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE category_route (
 category_id VARCHAR(64) NOT NULL, team_id VARCHAR(64) NOT NULL,
 route_order INT NOT NULL, effective_at DATETIME(6) NOT NULL, expired_at DATETIME(6),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY(category_id,team_id,effective_at),
 UNIQUE KEY uk_route_order(category_id,route_order,effective_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE consultation (
 session_id VARCHAR(32) PRIMARY KEY, creator_id VARCHAR(64) NOT NULL,
 category_id VARCHAR(64), status VARCHAR(32) NOT NULL, current_engineer_id VARCHAR(64),
 source VARCHAR(32) NOT NULL, resolution_type VARCHAR(32), converted_ticket_id VARCHAR(32),
 closed_at DATETIME(6), version BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 KEY idx_consult_creator(creator_id,status,created_at),
 KEY idx_consult_engineer(current_engineer_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE consultation_message (
 message_id VARCHAR(64) PRIMARY KEY, session_id VARCHAR(32) NOT NULL,
 sender_id VARCHAR(64), sender_type VARCHAR(32) NOT NULL, client_message_id VARCHAR(64) NOT NULL,
 content MEDIUMTEXT NOT NULL,
 citation_json JSON, sent_at DATETIME(6) NOT NULL, withdrawn_at DATETIME(6),
 withdraw_reason VARCHAR(2000), created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 KEY idx_consult_message(session_id,sent_at,message_id),
 UNIQUE KEY uk_consult_client_message(session_id,client_message_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ticket_draft (
 draft_id VARCHAR(64) PRIMARY KEY, creator_id VARCHAR(64) NOT NULL,
 nature VARCHAR(32), category_id VARCHAR(64), payload_json JSON NOT NULL,
 last_saved_at DATETIME(6) NOT NULL, expires_at DATETIME(6) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, UNIQUE KEY uk_active_draft(creator_id),
  title VARCHAR(100),
 description TEXT,
 impact_description TEXT,
 urgency_description TEXT,
 location VARCHAR(255),
 contact VARCHAR(255),
 asset_id VARCHAR(64)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE assignment (
 assignment_id VARCHAR(64) PRIMARY KEY, biz_type VARCHAR(32) NOT NULL,
 biz_id VARCHAR(64) NOT NULL, engineer_id VARCHAR(64) NOT NULL,
 assigned_at DATETIME(6) NOT NULL, response_deadline DATETIME(6),
 responded_at DATETIME(6), end_reason VARCHAR(32),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 KEY idx_assignment_object(biz_type,biz_id,assigned_at),
 KEY idx_assignment_engineer(engineer_id,end_reason)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sla_instance (
 sla_id VARCHAR(64) PRIMARY KEY, biz_type VARCHAR(32) NOT NULL,
 biz_id VARCHAR(64) NOT NULL, sla_type VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL,
 target_work_seconds BIGINT NOT NULL, elapsed_work_seconds BIGINT NOT NULL DEFAULT 0,
 paused_seconds BIGINT NOT NULL DEFAULT 0, target_at DATETIME(6),
 breached_at DATETIME(6), met_at DATETIME(6), calendar_id VARCHAR(64) NOT NULL,
 calendar_version BIGINT NOT NULL, version BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_sla_business(biz_type,biz_id,sla_type),
 KEY idx_sla_due(status,target_at),
  priority_snapshot VARCHAR(32),
 near_breach_notified TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sla_pause (
 pause_id VARCHAR(64) PRIMARY KEY, sla_id VARCHAR(64) NOT NULL,
 reason_type VARCHAR(32) NOT NULL, started_at DATETIME(6) NOT NULL,
 ended_at DATETIME(6), operator_id VARCHAR(64) NOT NULL,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 KEY idx_sla_pause(sla_id,started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE notification (
 notification_id VARCHAR(64) PRIMARY KEY, event_id VARCHAR(64) NOT NULL,
 receiver_id VARCHAR(64) NOT NULL, channel VARCHAR(32) NOT NULL,
 dedup_key VARCHAR(255) NOT NULL, status VARCHAR(32) NOT NULL,
 attempts INT NOT NULL DEFAULT 0, last_error VARCHAR(1000), sent_at DATETIME(6),
 read_at DATETIME(6), created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_notification_dedup(dedup_key), KEY idx_notification_receiver(receiver_id,status),
  title VARCHAR(100),
 content VARCHAR(500),
 action_url VARCHAR(200)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE audit_log (
 audit_id VARCHAR(64) PRIMARY KEY, actor_id VARCHAR(64), action VARCHAR(128) NOT NULL,
 object_type VARCHAR(64) NOT NULL, object_id VARCHAR(64) NOT NULL,
 before_json JSON, after_json JSON, reason VARCHAR(2000), request_id VARCHAR(128) NOT NULL,
 occurred_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 KEY idx_audit_object(object_type,object_id,occurred_at),
 KEY idx_audit_actor(actor_id,occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE idempotency_record (
 record_id VARCHAR(64) PRIMARY KEY, owner_id VARCHAR(64) NOT NULL,
 operation VARCHAR(128) NOT NULL, idempotency_key VARCHAR(128) NOT NULL,
 request_hash CHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, result_json JSON,
 expires_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_idempotency(owner_id,operation,idempotency_key),
 KEY idx_idempotency_expiry(expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE outbox_event (
 event_id VARCHAR(64) PRIMARY KEY, event_type VARCHAR(64) NOT NULL,
 aggregate_type VARCHAR(64) NOT NULL, aggregate_id VARCHAR(64) NOT NULL,
 event_version INT NOT NULL, aggregate_version BIGINT NOT NULL,
 payload_json JSON NOT NULL, status VARCHAR(32) NOT NULL,
 attempts INT NOT NULL DEFAULT 0, next_attempt_at DATETIME(6),
 published_at DATETIME(6), created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 KEY idx_outbox_publish(status,next_attempt_at),
 UNIQUE KEY uk_aggregate_version(aggregate_type,aggregate_id,aggregate_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE knowledge_article (
 article_id VARCHAR(64) PRIMARY KEY, status VARCHAR(32) NOT NULL,
 current_version_id VARCHAR(64), category_id VARCHAR(64) NOT NULL,
 risk_level VARCHAR(32) NOT NULL, version BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 KEY idx_knowledge_status(status,category_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE knowledge_version (
 version_id VARCHAR(64) PRIMARY KEY, article_id VARCHAR(64) NOT NULL,
 version_no INT NOT NULL, content_json JSON NOT NULL, author_id VARCHAR(64) NOT NULL,
 reviewer_id VARCHAR(64), published_at DATETIME(6), change_note VARCHAR(2000),
 platform_reviewer_id VARCHAR(64), platform_reviewed_at DATETIME(6),
 platform_review_decision VARCHAR(32),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_knowledge_version(article_id,version_no),
  search_text TEXT GENERATED ALWAYS AS (CONCAT_WS(' ', JSON_UNQUOTE(JSON_EXTRACT(content_json, '$.title')), JSON_UNQUOTE(JSON_EXTRACT(content_json, '$.summary')), JSON_UNQUOTE(JSON_EXTRACT(content_json, '$.keywords')), JSON_UNQUOTE(JSON_EXTRACT(content_json, '$.body')))) STORED,
 FULLTEXT KEY ft_knowledge_search(search_text) WITH PARSER ngram
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ai_interaction (
 interaction_id VARCHAR(64) PRIMARY KEY, session_id VARCHAR(32) NOT NULL,
 model_version VARCHAR(128) NOT NULL, retrieved_versions_json JSON NOT NULL,
 confidence DECIMAL(8,4), feedback VARCHAR(32), latency_ms BIGINT NOT NULL,
 occurred_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, KEY idx_ai_session(session_id,occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ticket (
  ticket_id VARCHAR(32) PRIMARY KEY, creator_id VARCHAR(64) NOT NULL,
  ticket_nature VARCHAR(32) NOT NULL, category_id VARCHAR(64) NOT NULL,
  title VARCHAR(100) NOT NULL, description TEXT NOT NULL,
  impact_description TEXT NOT NULL, urgency_description TEXT NOT NULL,
  location VARCHAR(255), contact VARCHAR(255), asset_id VARCHAR(64),
  status VARCHAR(32) NOT NULL, priority VARCHAR(32) NOT NULL,
  assignee_id VARCHAR(64), source_session_id VARCHAR(32),
  field_snapshot_json JSON, version BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
  completed_at DATETIME(6), closed_at DATETIME(6),
  KEY idx_ticket_creator_status (creator_id,status),
  KEY idx_ticket_assignee_status (assignee_id,status),
  KEY idx_ticket_priority_status (priority,status),
  category_snapshot VARCHAR(500),
 asset_check_status VARCHAR(32),
 impact_scope VARCHAR(32),
 urgency_level VARCHAR(32),
 auto_accepted TINYINT(1) NOT NULL DEFAULT 0,
 reopen_count INT NOT NULL DEFAULT 0,
 idempotency_key VARCHAR(128),
 first_response_at DATETIME(6),
 solved_at DATETIME(6),
 rating_score INT,
 rating_comment VARCHAR(2000),
 rated_at DATETIME(6),
 KEY idx_ticket_title_category(title,category_id,created_at),
 KEY idx_ticket_source_session(source_session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ticket_transition (
  transition_id VARCHAR(64) PRIMARY KEY, ticket_id VARCHAR(32) NOT NULL,
  from_status VARCHAR(32), to_status VARCHAR(32) NOT NULL,
  event_code VARCHAR(64) NOT NULL, operator_id VARCHAR(64) NOT NULL,
  reason TEXT, occurred_at DATETIME(6) NOT NULL,
  UNIQUE KEY uk_transition_order (ticket_id,occurred_at,transition_id),
  KEY idx_transition_ticket (ticket_id,occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE service_calendar (
  calendar_id VARCHAR(64) PRIMARY KEY, timezone VARCHAR(64) NOT NULL,
  work_week_json JSON NOT NULL, work_intervals_json JSON NOT NULL,
  lunch_pauses TINYINT(1) NOT NULL DEFAULT 1, version BIGINT NOT NULL DEFAULT 0,
  effective_from DATETIME(6) NOT NULL, effective_to DATETIME(6),
  created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE calendar_holiday (
  holiday_id VARCHAR(64) PRIMARY KEY, calendar_id VARCHAR(64) NOT NULL,
  holiday_date DATE NOT NULL, name VARCHAR(255) NOT NULL,
  is_working_day TINYINT(1) NOT NULL DEFAULT 0,
  UNIQUE KEY uk_calendar_date (calendar_id,holiday_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE exception_queue (
  exception_id VARCHAR(64) PRIMARY KEY, object_type VARCHAR(32) NOT NULL,
  object_id VARCHAR(64) NOT NULL, reason_code VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL, claimed_by VARCHAR(64), claimed_at DATETIME(6),
  resolved_by VARCHAR(64), resolved_at DATETIME(6), reason TEXT,
  created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
  KEY idx_exception_status (status,created_at),
  UNIQUE KEY uk_exception_open (object_type,object_id,reason_code,status),
  title VARCHAR(100),
 detail VARCHAR(1000),
 priority VARCHAR(32)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `attachment` (
  `attachment_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `biz_type` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'CONSULTATION/TICKET',
  `biz_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `uploader_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `size` bigint NOT NULL COMMENT '≤20MB',
  `hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '文件哈希',
  `scan_status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/CLEAN/REJECTED',
  `withdrawn_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`attachment_id`),
  KEY `idx_biz` (`biz_type`,`biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='附件（先扫描后可用；保存哈希/上传人/扫描结果）';

CREATE TABLE `case_candidate` (
  `case_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_type` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'TICKET/CONSULTATION',
  `source_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `structured_content` text COLLATE utf8mb4_unicode_ci COMMENT '现象/范围/根因/步骤/验证/关键词/分类',
  `masking_status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/MASKED',
  `reusable_flag` tinyint NOT NULL DEFAULT '0' COMMENT '工程师标记复用价值',
  `status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/PRIORITY/REVIEWED',
  `cluster_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`case_id`),
  KEY `idx_status` (`status`,`reusable_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='案例池（COMPLETED 工单自动进入 §16.1）';

CREATE TABLE `category_field_def` (
  `field_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `category_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `field_type` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'TEXT/RADIO/CHECKBOX/DATE/ATTACHMENT',
  `required` tinyint NOT NULL DEFAULT '0',
  `options` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '单选/多选值域 JSON',
  `sort_order` int NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`field_id`),
  KEY `idx_category` (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='分类扩展字段（每末级分类最多 10 个）';

CREATE TABLE `engineer_status_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `engineer_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'AVAILABLE/BUSY/AWAY/OFFLINE',
  `source` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'MANUAL/AUTO',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_engineer_time` (`engineer_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工程师状态变更（须保留时间和来源 §6.2）';

CREATE TABLE `knowledge_cluster` (
  `cluster_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `similarity_basis` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '类型/适用系统/现象/根因',
  `status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/MERGED/SUSPECTED',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cluster_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='知识簇（自动归簇不自动发布 §16.5）';

CREATE TABLE `ticket_field_value` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `ticket_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `field_definition_snapshot` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '提交时字段定义快照 §10.3',
  `field_value` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_ticket` (`ticket_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单扩展字段值（含定义快照）';

CREATE TABLE `ticket_message` (
  `message_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ticket_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sender_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `withdrawn_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`message_id`),
  KEY `idx_ticket_time` (`ticket_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单聊天（当前双方可见 §13.1）';

CREATE TABLE `work_calendar` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `cal_date` date NOT NULL,
  `day_type` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'WORKDAY/HOLIDAY',
  `start_time` time DEFAULT NULL COMMENT '默认 09:00',
  `end_time` time DEFAULT NULL COMMENT '默认 18:00',
  `lunch_pause` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_date` (`cal_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='服务日历（节假日平台管理员维护）';
