-- Generated by it-ticket-cloud/db/tools/build_schema.py from PRD 2.2 / DM / SQL-007 + SQL-010.
-- Complete 41-table contract. Fresh empty database only; not an existing-data migration.
-- Published V2_0/1/2 target the historical 34-table model only.
CREATE DATABASE IF NOT EXISTS it_ticket_system CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE it_ticket_system;
SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE `user` (
 user_id VARCHAR(64) PRIMARY KEY, employee_no VARCHAR(64) NOT NULL,
 name VARCHAR(255) NOT NULL, department_id VARCHAR(64) NOT NULL,
 status VARCHAR(32) NOT NULL, identity_source VARCHAR(64) NOT NULL,
 last_identity_sync_at DATETIME(6), version BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_user_employee_no(employee_no), KEY idx_user_department(department_id),
 KEY idx_user_status(status),
  password_hash VARCHAR(100) COMMENT 'Compatibility: local BCrypt authentication; remove after SSO rollout'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE user_role (
 user_id VARCHAR(64) NOT NULL, role_code VARCHAR(32) NOT NULL,
 granted_by VARCHAR(64) NOT NULL, granted_at DATETIME(6) NOT NULL,
 revoked_at DATETIME(6), created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY(user_id,role_code), KEY idx_role_revoked(revoked_at),
  CONSTRAINT ck_user_role_role_code CHECK (role_code IN ('EMPLOYEE','ENGINEER','PLATFORM_ADMIN','KNOWLEDGE_ADMIN'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE support_team (
 team_id VARCHAR(64) PRIMARY KEY, name VARCHAR(255) NOT NULL, status VARCHAR(32) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, UNIQUE KEY uk_team_name(name), KEY idx_team_status(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE team_member (
 team_id VARCHAR(64) NOT NULL, engineer_id VARCHAR(64) NOT NULL,
 joined_at DATETIME(6) NOT NULL, left_at DATETIME(6), status VARCHAR(32) NOT NULL,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY(team_id,engineer_id), KEY idx_member_engineer(engineer_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE engineer_runtime_state (
 engineer_id VARCHAR(64) PRIMARY KEY, presence VARCHAR(32) NOT NULL,
 last_activity_at DATETIME(6), last_assigned_at DATETIME(6),
 version BIGINT NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, KEY idx_engineer_presence(presence,last_activity_at),
  CONSTRAINT ck_engineer_runtime_state_presence CHECK (presence IN ('AVAILABLE','BUSY','AWAY','OFFLINE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE engineer_category_capability (
 engineer_id VARCHAR(64) NOT NULL, category_id VARCHAR(64) NOT NULL,
 team_id VARCHAR(64) NOT NULL, enabled TINYINT(1) NOT NULL,
 effective_at DATETIME(6) NOT NULL, expired_at DATETIME(6),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY(engineer_id,category_id,team_id,effective_at),
 KEY idx_capability_route(category_id,team_id,enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE category (
 category_id VARCHAR(64) PRIMARY KEY, parent_id VARCHAR(64),
 ticket_nature VARCHAR(32) NOT NULL, name VARCHAR(255) NOT NULL, level SMALLINT NOT NULL,
 definition_version VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, KEY idx_category_parent(parent_id,level,status),
  CONSTRAINT ck_category_ticket_nature CHECK (ticket_nature IN ('INCIDENT','SERVICE_REQUEST'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE category_route (
 category_id VARCHAR(64) NOT NULL, team_id VARCHAR(64) NOT NULL,
 route_order INT NOT NULL, effective_at DATETIME(6) NOT NULL, expired_at DATETIME(6),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY(category_id,team_id,effective_at),
 UNIQUE KEY uk_route_order(category_id,route_order,effective_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE field_definition (
 field_definition_id VARCHAR(64) PRIMARY KEY, category_id VARCHAR(64) NOT NULL,
 field_key VARCHAR(128) NOT NULL, field_type VARCHAR(32) NOT NULL,
 required TINYINT(1) NOT NULL, options_json JSON, display_order INT NOT NULL,
 enabled TINYINT(1) NOT NULL, definition_version VARCHAR(64) NOT NULL,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_field_version(category_id,field_key,definition_version),
 KEY idx_field_category(category_id,enabled,display_order),
  CONSTRAINT ck_field_definition_field_type CHECK (field_type IN ('TEXT','SINGLE_SELECT','MULTI_SELECT','DATE','ATTACHMENT'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ai_provider_config (
 provider_config_id VARCHAR(64) PRIMARY KEY, provider_id VARCHAR(64) NOT NULL,
 config_version BIGINT NOT NULL, status VARCHAR(32) NOT NULL,
 base_url VARCHAR(512) NOT NULL, api_key_secret_ref VARCHAR(255) NOT NULL,
 model VARCHAR(128) NOT NULL, embedding_model VARCHAR(128), protocol_version VARCHAR(64) NOT NULL,
 path_json JSON NOT NULL, capability_json JSON NOT NULL, timeout_json JSON NOT NULL,
 generation_json JSON NOT NULL, created_by VARCHAR(64) NOT NULL, created_at DATETIME(6) NOT NULL,
 validated_by VARCHAR(64), validated_at DATETIME(6), activated_by VARCHAR(64), activated_at DATETIME(6),
  retired_at DATETIME(6), rollback_from_version BIGINT, audit_request_id VARCHAR(128) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  active_provider_id VARCHAR(64) GENERATED ALWAYS AS (CASE WHEN status='ACTIVE' THEN provider_id ELSE NULL END) STORED,
  UNIQUE KEY uk_provider_active(active_provider_id),
 UNIQUE KEY uk_provider_version(provider_id,config_version), KEY idx_provider_status(provider_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE consultation (
 session_id VARCHAR(32) PRIMARY KEY, creator_id VARCHAR(64) NOT NULL,
 category_id VARCHAR(64), status VARCHAR(32) NOT NULL, current_engineer_id VARCHAR(64),
 source VARCHAR(32) NOT NULL, resolved_type VARCHAR(32), converted_ticket_id VARCHAR(32),
 closed_at DATETIME(6), version BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 KEY idx_consult_creator(creator_id,status,created_at),
 KEY idx_consult_engineer(current_engineer_id,status),
  CONSTRAINT ck_consultation_status CHECK (status IN ('AI_ACTIVE','WAITING_ENGINEER','HUMAN_ACTIVE','PENDING_CONFIRMATION','RESOLVED','CONVERTED_TO_TICKET','CLOSED')),
 CONSTRAINT ck_consultation_source CHECK (source IN ('AI','HUMAN_DIRECT','TICKET_FOLLOW_UP')),
 CONSTRAINT ck_consultation_resolved_type CHECK (resolved_type IN ('EMPLOYEE_CONFIRMED','AUTO_RESOLVED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE consultation_message (
 message_id VARCHAR(64) PRIMARY KEY, session_id VARCHAR(32) NOT NULL,
 sender_id VARCHAR(64), sender_type VARCHAR(32) NOT NULL, client_message_id VARCHAR(64) NOT NULL,
 content MEDIUMTEXT NOT NULL,
 citation_json JSON, sent_at DATETIME(6) NOT NULL, withdrawn_at DATETIME(6),
 withdraw_reason VARCHAR(2000), created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 KEY idx_consult_message(session_id,sent_at,message_id),
 UNIQUE KEY uk_consult_client_message(session_id,client_message_id),
  CONSTRAINT ck_consultation_message_sender_type CHECK (sender_type IN ('EMPLOYEE','ENGINEER','AI','SYSTEM'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ticket (
  ticket_id VARCHAR(32) PRIMARY KEY, creator_id VARCHAR(64) NOT NULL,
  nature VARCHAR(32) NOT NULL, category_id VARCHAR(64) NOT NULL,
  title VARCHAR(100) NOT NULL, description TEXT NOT NULL,
  impact_description TEXT NOT NULL, urgency_description TEXT NOT NULL,
  location VARCHAR(255), contact VARCHAR(255), asset_id VARCHAR(64),
  status VARCHAR(32) NOT NULL, priority VARCHAR(32) NOT NULL,
  assignee_id VARCHAR(64), source_session_id VARCHAR(32),
  field_definition_snapshot JSON, version BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
  completed_at DATETIME(6), closed_at DATETIME(6),
  KEY idx_ticket_creator_status (creator_id,status),
  KEY idx_ticket_assignee_status (assignee_id,status),
  KEY idx_ticket_priority_status (priority,status),
  category_snapshot VARCHAR(500),
 asset_check_status VARCHAR(32),
 impact_scope VARCHAR(32),
 urgency_level VARCHAR(32),
 auto_accepted TINYINT(1) NOT NULL DEFAULT 0,
 reopen_count INT NOT NULL DEFAULT 0,
 idempotency_key VARCHAR(128),
 first_response_at DATETIME(6),
 solved_at DATETIME(6),
 rating_score INT,
 rating_comment VARCHAR(2000),
 rated_at DATETIME(6),
 KEY idx_ticket_title_category(title,category_id,created_at),
 KEY idx_ticket_source_session(source_session_id),
 CONSTRAINT ck_ticket_nature CHECK (nature IN ('INCIDENT','SERVICE_REQUEST')),
 CONSTRAINT ck_ticket_status CHECK (status IN ('NEW','ASSIGNED','IN_PROGRESS','PENDING_SUPPLEMENT','PENDING_EXTERNAL','PENDING_ACCEPTANCE','COMPLETED','CANCELLED','CLOSED')),
 CONSTRAINT ck_ticket_priority CHECK (priority IN ('HIGH','MEDIUM','LOW'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ticket_field_value (
  ticket_id VARCHAR(32) NOT NULL, field_definition_id VARCHAR(64) NOT NULL,
  field_key VARCHAR(128) NOT NULL, field_definition_snapshot JSON NOT NULL, field_value JSON NOT NULL,
  definition_version VARCHAR(64) NOT NULL, created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (ticket_id,field_definition_id),
  KEY idx_field_lookup (field_definition_id,field_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ticket_transition (
  transition_id VARCHAR(64) PRIMARY KEY, ticket_id VARCHAR(32) NOT NULL,
  from_status VARCHAR(32), to_status VARCHAR(32) NOT NULL,
  event VARCHAR(64) NOT NULL, operator_id VARCHAR(64) NOT NULL,
  reason TEXT, occurred_at DATETIME(6) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY uk_transition_order (ticket_id,occurred_at,transition_id),
  KEY idx_transition_ticket (ticket_id,occurred_at),
  CONSTRAINT ck_ticket_transition_from_status CHECK (from_status IN ('NEW','ASSIGNED','IN_PROGRESS','PENDING_SUPPLEMENT','PENDING_EXTERNAL','PENDING_ACCEPTANCE','COMPLETED','CANCELLED','CLOSED')),
 CONSTRAINT ck_ticket_transition_to_status CHECK (to_status IN ('NEW','ASSIGNED','IN_PROGRESS','PENDING_SUPPLEMENT','PENDING_EXTERNAL','PENDING_ACCEPTANCE','COMPLETED','CANCELLED','CLOSED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ticket_duplicate (
  relation_id VARCHAR(64) PRIMARY KEY, source_ticket_id VARCHAR(32) NOT NULL,
  master_ticket_id VARCHAR(32) NOT NULL, reason VARCHAR(2000) NOT NULL,
  created_by VARCHAR(64) NOT NULL, created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  UNIQUE KEY uk_duplicate_source (source_ticket_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE attachment_access (
  access_id VARCHAR(64) PRIMARY KEY, attachment_id VARCHAR(64) NOT NULL,
  subject_id VARCHAR(64) NOT NULL, request_id VARCHAR(128) NOT NULL,
  expires_at DATETIME(6) NOT NULL, accessed_at DATETIME(6),
  access_result VARCHAR(32), revoked_at DATETIME(6), issued_at DATETIME(6) NOT NULL,
  created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
  KEY idx_attachment_access (attachment_id,subject_id,expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE service_calendar (
  calendar_id VARCHAR(64) PRIMARY KEY, timezone VARCHAR(64) NOT NULL,
  work_week_json JSON NOT NULL, work_intervals_json JSON NOT NULL,
  lunch_pauses TINYINT(1) NOT NULL DEFAULT 1, version BIGINT NOT NULL DEFAULT 0,
  effective_from DATETIME(6) NOT NULL, effective_to DATETIME(6),
  created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE calendar_holiday (
  holiday_id VARCHAR(64) PRIMARY KEY, calendar_id VARCHAR(64) NOT NULL,
  holiday_date DATE NOT NULL, name VARCHAR(255) NOT NULL,
  is_working_day TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY uk_calendar_date (calendar_id,holiday_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE exception_queue (
  exception_id VARCHAR(64) PRIMARY KEY, object_type VARCHAR(32) NOT NULL,
  object_id VARCHAR(64) NOT NULL, reason_code VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL, claimed_by VARCHAR(64), claimed_at DATETIME(6),
  resolved_by VARCHAR(64), resolved_at DATETIME(6), reason TEXT,
  created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
  KEY idx_exception_status (status,created_at),
  UNIQUE KEY uk_exception_open (object_type,object_id,reason_code,status),
  title VARCHAR(100),
 detail VARCHAR(1000),
 priority VARCHAR(32)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE outbox_delivery (
  delivery_id VARCHAR(64) PRIMARY KEY, event_id VARCHAR(64) NOT NULL,
  stream_name VARCHAR(128) NOT NULL, consumer_group VARCHAR(128) NOT NULL,
  entry_id VARCHAR(128), status VARCHAR(32) NOT NULL,
  attempts INT NOT NULL DEFAULT 0, last_error VARCHAR(1000),
  next_attempt_at DATETIME(6), acked_at DATETIME(6),
  created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
  UNIQUE KEY uk_delivery_event_group (event_id,consumer_group),
  KEY idx_delivery_retry (status,next_attempt_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ticket_message (
 message_id VARCHAR(64) PRIMARY KEY, ticket_id VARCHAR(32) NOT NULL,
 sender_id VARCHAR(64), sender_type VARCHAR(32) NOT NULL, client_message_id VARCHAR(64) NOT NULL,
 content MEDIUMTEXT NOT NULL,
 sent_at DATETIME(6) NOT NULL, withdrawn_at DATETIME(6), withdraw_reason VARCHAR(2000),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 KEY idx_ticket_message(ticket_id,sent_at,message_id),
 UNIQUE KEY uk_ticket_client_message(ticket_id,client_message_id),
  CONSTRAINT ck_ticket_message_sender_type CHECK (sender_type IN ('EMPLOYEE','ENGINEER','AI','SYSTEM'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ticket_draft (
  draft_id VARCHAR(64) PRIMARY KEY, creator_id VARCHAR(64) NOT NULL,
  ticket_nature VARCHAR(32), category_id VARCHAR(64), payload_json JSON NOT NULL,
 last_saved_at DATETIME(6) NOT NULL, expires_at DATETIME(6) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, UNIQUE KEY uk_active_draft(creator_id),
  title VARCHAR(100),
 description TEXT,
 impact_description TEXT,
 urgency_description TEXT,
 location VARCHAR(255),
 contact VARCHAR(255),
 asset_id VARCHAR(64),
 CONSTRAINT ck_ticket_draft_ticket_nature CHECK (ticket_nature IN ('INCIDENT','SERVICE_REQUEST'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE supplement_request (
 request_id VARCHAR(64) PRIMARY KEY, ticket_id VARCHAR(32) NOT NULL,
 sequence_no INT NOT NULL, requested_by VARCHAR(64) NOT NULL, content TEXT NOT NULL,
 requested_at DATETIME(6) NOT NULL, responded_at DATETIME(6),
 overdue_closed TINYINT(1) NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, UNIQUE KEY uk_supplement_seq(ticket_id,sequence_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE external_wait (
 wait_id VARCHAR(64) PRIMARY KEY, ticket_id VARCHAR(32) NOT NULL,
 dependency_type VARCHAR(32) NOT NULL, reason VARCHAR(2000) NOT NULL,
 expected_at DATETIME(6) NOT NULL, started_at DATETIME(6) NOT NULL,
 ended_at DATETIME(6), resume_note VARCHAR(2000),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 KEY idx_external_wait(ticket_id,started_at),
  CONSTRAINT ck_external_wait_dependency_type CHECK (dependency_type IN ('SPARE_PART','VENDOR','CARRIER','OTHER'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ticket_resolution (
 resolution_id VARCHAR(64) PRIMARY KEY, ticket_id VARCHAR(32) NOT NULL,
 solution MEDIUMTEXT NOT NULL, verification TEXT NOT NULL, submitted_by VARCHAR(64) NOT NULL,
 submitted_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, KEY idx_resolution(ticket_id,submitted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ticket_acceptance (
 acceptance_id VARCHAR(64) PRIMARY KEY, ticket_id VARCHAR(32) NOT NULL,
 result VARCHAR(32) NOT NULL, reason VARCHAR(2000), operator_id VARCHAR(64),
 occurred_at DATETIME(6) NOT NULL, rating_score TINYINT,
 rating_comment VARCHAR(2000), rated_at DATETIME(6), created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, KEY idx_acceptance(ticket_id,occurred_at),
  CONSTRAINT ck_ticket_acceptance_result CHECK (result IN ('ACCEPTED','REJECTED','AUTO_ACCEPTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE attachment (
 attachment_id VARCHAR(64) PRIMARY KEY, biz_type VARCHAR(32) NOT NULL,
 biz_id VARCHAR(64) NOT NULL, uploader_id VARCHAR(64) NOT NULL,
 object_key VARCHAR(512) NOT NULL, file_name VARCHAR(255) NOT NULL,
 size BIGINT NOT NULL, hash CHAR(64) NOT NULL, content_type VARCHAR(255) NOT NULL,
 scan_status VARCHAR(32) NOT NULL, uploaded_at DATETIME(6) NOT NULL,
 withdrawn_at DATETIME(6), created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_attachment_hash(biz_type,biz_id,hash), UNIQUE KEY uk_object_key(object_key),
  CONSTRAINT ck_attachment_biz_type CHECK (biz_type IN ('CONSULTATION','TICKET','MESSAGE','SUPPLEMENT','KNOWLEDGE')),
 CONSTRAINT ck_attachment_scan_status CHECK (scan_status IN ('PENDING','PASSED','REJECTED','ERROR'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE assignment (
 assignment_id VARCHAR(64) PRIMARY KEY, biz_type VARCHAR(32) NOT NULL,
 biz_id VARCHAR(64) NOT NULL, engineer_id VARCHAR(64) NOT NULL,
 assigned_at DATETIME(6) NOT NULL, response_deadline DATETIME(6),
 responded_at DATETIME(6), end_reason VARCHAR(32),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_assignment_attempt(biz_type,biz_id,engineer_id,assigned_at),
 KEY idx_assignment_object(biz_type,biz_id,assigned_at),
 KEY idx_assignment_engineer(engineer_id,end_reason),
  CONSTRAINT ck_assignment_biz_type CHECK (biz_type IN ('CONSULTATION','TICKET')),
 CONSTRAINT ck_assignment_end_reason CHECK (end_reason IN ('RESPONDED','TIMEOUT','TRANSFERRED','CANCELLED','COMPLETED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sla_instance (
 sla_id VARCHAR(64) PRIMARY KEY, ticket_id VARCHAR(32), biz_type VARCHAR(32) NOT NULL,
 biz_id VARCHAR(64) NOT NULL, sla_type VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL,
 target_work_seconds BIGINT NOT NULL, elapsed_work_seconds BIGINT NOT NULL DEFAULT 0,
 paused_seconds BIGINT NOT NULL DEFAULT 0, target_at DATETIME(6),
 breach_at DATETIME(6), met_at DATETIME(6), calendar_id VARCHAR(64) NOT NULL,
 calendar_version BIGINT NOT NULL, version BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_sla_business(biz_type,biz_id,sla_type),
 KEY idx_sla_due(status,target_at),
 KEY idx_sla_ticket(ticket_id),
  priority_snapshot VARCHAR(32),
 near_breach_notified TINYINT(1) NOT NULL DEFAULT 0,
 CONSTRAINT ck_sla_instance_biz_type CHECK (biz_type IN ('CONSULTATION','TICKET')),
 CONSTRAINT ck_sla_instance_sla_type CHECK (sla_type IN ('CONSULTATION_RESPONSE','TICKET_RESPONSE','TICKET_COMPLETION')),
 CONSTRAINT ck_sla_instance_status CHECK (status IN ('RUNNING','PAUSED','MET','BREACHED','CANCELLED')),
 CONSTRAINT ck_sla_business_link CHECK ((biz_type='TICKET' AND ticket_id IS NOT NULL AND ticket_id=biz_id) OR (biz_type='CONSULTATION' AND ticket_id IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sla_pause (
 pause_id VARCHAR(64) PRIMARY KEY, sla_id VARCHAR(64) NOT NULL,
 reason_type VARCHAR(32) NOT NULL, started_at DATETIME(6) NOT NULL,
 ended_at DATETIME(6), operator_id VARCHAR(64) NOT NULL,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 KEY idx_sla_pause(sla_id,started_at),
  CONSTRAINT ck_sla_pause_reason_type CHECK (reason_type IN ('PENDING_SUPPLEMENT','PENDING_EXTERNAL'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE notification (
 notification_id VARCHAR(64) PRIMARY KEY, event_id VARCHAR(64) NOT NULL,
 receiver_id VARCHAR(64) NOT NULL, channel VARCHAR(32) NOT NULL,
 dedup_key VARCHAR(255) NOT NULL, status VARCHAR(32) NOT NULL,
 attempts INT NOT NULL DEFAULT 0, last_error VARCHAR(1000), sent_at DATETIME(6),
 read_at DATETIME(6), created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_notification_dedup(dedup_key), KEY idx_notification_receiver(receiver_id,status),
  title VARCHAR(100),
 content VARCHAR(500),
 action_url VARCHAR(200),
 CONSTRAINT ck_notification_channel CHECK (channel IN ('IN_APP','EMAIL')),
 CONSTRAINT ck_notification_status CHECK (status IN ('PENDING','SENT','FAILED','DEAD_LETTER'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE audit_log (
 audit_id VARCHAR(64) PRIMARY KEY, actor_id VARCHAR(64), action VARCHAR(128) NOT NULL,
 object_type VARCHAR(64) NOT NULL, object_id VARCHAR(64) NOT NULL,
 before_value JSON, after_value JSON, reason VARCHAR(2000), request_id VARCHAR(128) NOT NULL,
 occurred_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 KEY idx_audit_object(object_type,object_id,occurred_at),
 KEY idx_audit_actor(actor_id,occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE idempotency_record (
 record_id VARCHAR(64) PRIMARY KEY, owner_id VARCHAR(64) NOT NULL,
 operation VARCHAR(128) NOT NULL, idempotency_key VARCHAR(128) NOT NULL,
 request_hash CHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, result_json JSON,
 expires_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_idempotency(owner_id,operation,idempotency_key),
 KEY idx_idempotency_expiry(expires_at),
  CONSTRAINT ck_idempotency_record_status CHECK (status IN ('IN_PROGRESS','SUCCEEDED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE outbox_event (
 event_id VARCHAR(64) PRIMARY KEY, event_type VARCHAR(64) NOT NULL,
 aggregate_type VARCHAR(64) NOT NULL, aggregate_id VARCHAR(64) NOT NULL,
 event_version INT NOT NULL, aggregate_version BIGINT NOT NULL,
 payload_json JSON NOT NULL, status VARCHAR(32) NOT NULL,
 attempts INT NOT NULL DEFAULT 0, next_attempt_at DATETIME(6),
 published_at DATETIME(6), created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 KEY idx_outbox_publish(status,next_attempt_at),
 UNIQUE KEY uk_aggregate_version(aggregate_type,aggregate_id,aggregate_version),
  CONSTRAINT ck_outbox_event_status CHECK (status IN ('PENDING','PUBLISHED','FAILED','DEAD_LETTER'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE case_candidate (
 case_id VARCHAR(64) PRIMARY KEY, source_type VARCHAR(32) NOT NULL,
 source_id VARCHAR(64) NOT NULL, structured_content JSON NOT NULL,
 masking_status VARCHAR(32) NOT NULL, reusable_flag TINYINT(1) NOT NULL,
 status VARCHAR(32) NOT NULL, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, UNIQUE KEY uk_case_source(source_type,source_id),
  CONSTRAINT ck_case_candidate_source_type CHECK (source_type IN ('CONSULTATION','TICKET')),
 CONSTRAINT ck_case_candidate_masking_status CHECK (masking_status IN ('NOT_STARTED','IN_PROGRESS','PASSED','FAILED')),
 CONSTRAINT ck_case_candidate_status CHECK (status IN ('PENDING_MASKING','PENDING_REVIEW','REJECTED','ACCEPTED','DISCARDED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE knowledge_article (
 article_id VARCHAR(64) PRIMARY KEY, status VARCHAR(32) NOT NULL,
 current_version_id VARCHAR(64), category_id VARCHAR(64) NOT NULL,
 risk_level VARCHAR(32) NOT NULL, version BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 KEY idx_knowledge_status(status,category_id),
  CONSTRAINT ck_knowledge_article_status CHECK (status IN ('DRAFT','PENDING_REVIEW','PUBLISHED','OFFLINE')),
 CONSTRAINT ck_knowledge_article_risk_level CHECK (risk_level IN ('NORMAL','HIGH'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE knowledge_version (
 version_id VARCHAR(64) PRIMARY KEY, article_id VARCHAR(64) NOT NULL,
 version_no INT NOT NULL, content JSON NOT NULL, author_id VARCHAR(64) NOT NULL,
 reviewer_id VARCHAR(64), published_at DATETIME(6), change_note VARCHAR(2000),
 platform_reviewer_id VARCHAR(64), platform_reviewed_at DATETIME(6),
 platform_review_decision VARCHAR(32),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY uk_knowledge_version(article_id,version_no),
  search_text TEXT GENERATED ALWAYS AS (CONCAT_WS(' ', JSON_UNQUOTE(JSON_EXTRACT(content, '$.title')), JSON_UNQUOTE(JSON_EXTRACT(content, '$.summary')), JSON_UNQUOTE(JSON_EXTRACT(content, '$.keywords')), JSON_UNQUOTE(JSON_EXTRACT(content, '$.body')))) STORED,
 FULLTEXT KEY ft_knowledge_search(search_text) WITH PARSER ngram
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE knowledge_cluster (
 cluster_id VARCHAR(64) PRIMARY KEY, similarity_basis JSON NOT NULL,
 status VARCHAR(32) NOT NULL, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, KEY idx_cluster_status(status),
  CONSTRAINT ck_knowledge_cluster_status CHECK (status IN ('OPEN','MERGED','DISMISSED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ai_interaction (
 interaction_id VARCHAR(64) PRIMARY KEY, session_id VARCHAR(32) NOT NULL,
 model_version VARCHAR(128) NOT NULL, retrieved_versions JSON NOT NULL,
 confidence DECIMAL(8,4), feedback VARCHAR(32), latency BIGINT NOT NULL,
 occurred_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL, KEY idx_ai_session(session_id,occurred_at),
  CONSTRAINT ck_ai_interaction_feedback CHECK (feedback IN ('HELPFUL','NOT_HELPFUL','INCORRECT'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE rag_index_pointer (
 pointer_id VARCHAR(64) PRIMARY KEY, article_id VARCHAR(64) NOT NULL, knowledge_version_id VARCHAR(64) NOT NULL,
 index_version VARCHAR(128) NOT NULL, status VARCHAR(32) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0, activated_at DATETIME(6), offlined_at DATETIME(6),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 active_article_id VARCHAR(64) GENERATED ALWAYS AS (CASE WHEN status='ACTIVE' THEN article_id ELSE NULL END) STORED,
 UNIQUE KEY uk_rag_pointer_knowledge(knowledge_version_id),
 UNIQUE KEY uk_rag_pointer_active_article(active_article_id),
 UNIQUE KEY uk_rag_pointer_active_index(index_version,status),
 KEY idx_rag_pointer_status(status,updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
