"""Render the additive 470ce57 -> PRD 2.2 unified-field migration, without touching V2_0/1.

Changed tables are copied and atomically switched; source facts remain in
legacy_v2_* tables. No timestamps or untouched tables are rewritten.
"""
import hashlib
from build_schema import DB, canonical, tables, columns

CHANGED = {'user': 'user_account', 'support_team': 'support_team',
           'team_member': 'team_member', 'category': 'category',
           'ticket': 'ticket', 'ticket_draft': 'ticket_draft',
           'consultation': 'consultation', 'ticket_transition': 'ticket_transition',
           'sla_instance': 'sla_instance', 'knowledge_version': 'knowledge_version',
           'ai_interaction': 'ai_interaction', 'audit_log': 'audit_log'}
RENAMED = {'user': {'name': 'display_name'}, 'category': {'ticket_nature': 'nature'},
           'ticket': {'field_definition_snapshot': 'field_snapshot_json', 'nature': 'ticket_nature'},
           'ticket_draft': {'ticket_nature': 'nature'},
           'consultation': {'resolved_type': 'resolution_type'},
           'ticket_transition': {'event': 'event_code'},
           'sla_instance': {'breach_at': 'breached_at'},
           'knowledge_version': {'content': 'content_json'},
           'ai_interaction': {'retrieved_versions': 'retrieved_versions_json', 'latency': 'latency_ms'},
           'audit_log': {'before_value': 'before_json', 'after_value': 'after_json'}}
Q = lambda name: '`' + name + '`'


def render():
    current = canonical()
    old = tables((DB/'tests/fixtures/canonical-470ce57-schema.sql').read_text(encoding='utf-8'))
    checksum = hashlib.sha256('\n'.join(current[n] for n in CHANGED).encode()).hexdigest()
    sql = """-- Generated by db/tools/build_latest_migration.py; 470ce57 -> PRD 2.2 unified fields (a99ab6a plus approved PRD alignment).
-- Run after V2_1 for 388f51d, or against the frozen 470ce57 baseline.
-- Stop writers throughout. Fail fast; never mysql --force. See db/README.md.
USE it_ticket_system;
SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET SESSION sql_mode = 'STRICT_ALL_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE TABLE IF NOT EXISTS schema_migration_audit (
 version VARCHAR(32) PRIMARY KEY, checksum CHAR(64) NOT NULL,
 operator_id VARCHAR(128) NOT NULL, source_timezone VARCHAR(64) NOT NULL,
 started_at DATETIME(6) NOT NULL, completed_at DATETIME(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DELIMITER $$
CREATE PROCEDURE migration_v2_2_guard()
BEGIN
 IF COALESCE(GET_LOCK(CONCAT(DATABASE(),'.schema_v2'),0),0)<>1 THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Another schema migration owns the advisory lock';
 END IF;
 IF COALESCE(@main_writes_stopped,0)<>1 OR COALESCE(@migration_operator,'')='' THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Require stopped writers and named migration operator';
 END IF;
 IF EXISTS (SELECT 1 FROM schema_migration_audit WHERE version='V2_2') THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V2_2 already applied; do not replay';
 END IF;
 IF COALESCE(@canonical_source_revision,'')<>'470ce57' THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Verify frozen 470ce57 source schema and set canonical_source_revision';
 END IF;
 IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='user') THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Target user table already exists; inspect source revision';
 END IF;
"""
    for target, source in CHANGED.items():
        for col in columns(old[source]):
            sql += f" IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='{source}' AND column_name='{col}') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Missing frozen source column {source}.{col}'; END IF;\n"
        sql += f" IF (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='{source}')<>{len(columns(old[source]))} THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unexpected source columns: {source}'; END IF;\n"
        if target == 'sla_instance':
            sql += " IF EXISTS (SELECT 1 FROM sla_instance WHERE biz_type NOT IN ('TICKET','CONSULTATION') OR (biz_type='TICKET' AND CHAR_LENGTH(biz_id)>32)) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Invalid SLA business association'; END IF;\n"
        if 'enabled' in columns(old[source]):
            sql += f" IF EXISTS (SELECT 1 FROM {Q(source)} WHERE enabled IS NULL OR enabled NOT IN (0,1)) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unknown enabled value: {source}; explicit mapping required'; END IF;\n"
    sql += "END$$\nDELIMITER ;\nCALL migration_v2_2_guard();\nDROP PROCEDURE migration_v2_2_guard;\n"
    for target in CHANGED:
        ddl = current[target]
        start = ddl.index('(')
        sql += '\nCREATE TABLE ' + Q('v2_2_stage_'+target) + ' ' + ddl[start:] + '\n'
    sql += "\nDELIMITER $$\nCREATE PROCEDURE migration_v2_2_copy()\nBEGIN\n DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;\n START TRANSACTION;\n"
    for target, source in CHANGED.items():
        names = [name for name, definition in columns(current[target]).items() if 'GENERATED ALWAYS' not in definition]
        expr = []
        for col in names:
            if target == 'sla_instance' and col == 'ticket_id':
                expr.append("CASE WHEN biz_type='TICKET' THEN biz_id ELSE NULL END")
            elif col == 'status' and 'enabled' in columns(old[source]):
                expr.append("CASE enabled WHEN 1 THEN 'ACTIVE' WHEN 0 THEN 'DISABLED' END")
            else:
                expr.append(Q(RENAMED.get(target, {}).get(col, col)))
        sql += f" INSERT INTO {Q('v2_2_stage_'+target)} ({','.join(map(Q,names))}) SELECT {','.join(expr)} FROM {Q(source)};\n"
        sql += f" IF (SELECT COUNT(*) FROM {Q(source)})<>(SELECT COUNT(*) FROM {Q('v2_2_stage_'+target)}) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V2_2 row-count mismatch: {source}'; END IF;\n"
    sql += " COMMIT;\nEND$$\nDELIMITER ;\nCALL migration_v2_2_copy();\nDROP PROCEDURE migration_v2_2_copy;\n"
    renames = [f'{Q(source)} TO {Q("legacy_v2_"+source)}' for source in CHANGED.values()]
    renames += [f'{Q("v2_2_stage_"+target)} TO {Q(target)}' for target in CHANGED]
    sql += '\nRENAME TABLE\n '+',\n '.join(renames)+';\n'
    sql += f"INSERT INTO schema_migration_audit (version,checksum,operator_id,source_timezone,started_at,completed_at) VALUES ('V2_2','{checksum}',@migration_operator,'+00:00',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6));\n"
    sql += "DO RELEASE_LOCK(CONCAT(DATABASE(),'.schema_v2'));\n"
    (DB/'migration/V2_2__align_prd_field_names.sql').write_text(sql, encoding='utf-8')


if __name__ == '__main__':
    render()
