"""Render the reviewed SQL-007/010 baseline; never connects to a database.

Run from any directory: python it-ticket-cloud/db/tools/build_schema.py
The compatibility fields below are documented in specs/11-main-schema-alignment.md.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[3]
DB = ROOT / 'it-ticket-cloud/db'

# User scope: align implemented modules only. An entity/mapper or live service query
# exists for every table here. Attachment is list-only and retains its old schema.
IMPLEMENTED = set('user user_role support_team team_member engineer_runtime_state engineer_category_capability category category_route consultation consultation_message ticket ticket_transition ticket_draft assignment sla_instance sla_pause service_calendar calendar_holiday exception_queue notification audit_log idempotency_record outbox_event knowledge_article knowledge_version ai_interaction'.split())


def tables(sql):
    return {m.group(1): m.group(0) for m in re.finditer(
        r'CREATE TABLE\s+`?(\w+)`?\s*\([\s\S]+?\) ENGINE=[^;]+;', sql, re.I)}


def parts(ddl):
    body = ddl[ddl.index('(') + 1:ddl.rindex(') ENGINE=')]
    result, start, depth, quote = [], 0, 0, None
    for i, c in enumerate(body):
        if quote:
            if c == quote and (i == 0 or body[i - 1] != '\\'):
                quote = None
        elif c in "'\"`":
            quote = c
        elif c == '(':
            depth += 1
        elif c == ')':
            depth -= 1
        elif c == ',' and depth == 0:
            result.append(body[start:i].strip())
            start = i + 1
    result.append(body[start:].strip())
    return result


def columns(ddl):
    return {p.split()[0].strip('`'): p for p in parts(ddl)
            if not re.match(r'^(PRIMARY|UNIQUE|KEY|INDEX|FULLTEXT|CONSTRAINT|CHECK)\b', p, re.I)}


EXTRAS = {
    'user': ["password_hash VARCHAR(100) COMMENT 'Compatibility: local BCrypt authentication; remove after SSO rollout'"],
    'ticket': [
        'category_snapshot VARCHAR(500)', 'asset_check_status VARCHAR(32)',
        'impact_scope VARCHAR(32)', 'urgency_level VARCHAR(32)',
        'auto_accepted TINYINT(1) NOT NULL DEFAULT 0', 'reopen_count INT NOT NULL DEFAULT 0',
        'idempotency_key VARCHAR(128)', 'first_response_at DATETIME(6)',
        'solved_at DATETIME(6)', 'rating_score INT', 'rating_comment VARCHAR(2000)',
        'rated_at DATETIME(6)', 'KEY idx_ticket_title_category(title,category_id,created_at)',
        'KEY idx_ticket_source_session(source_session_id)',
    ],
    'ticket_draft': ['title VARCHAR(100)', 'description TEXT', 'impact_description TEXT',
                     'urgency_description TEXT', 'location VARCHAR(255)', 'contact VARCHAR(255)', 'asset_id VARCHAR(64)'],
    'sla_instance': ['priority_snapshot VARCHAR(32)', 'near_breach_notified TINYINT(1) NOT NULL DEFAULT 0'],
    'notification': ['title VARCHAR(100)', 'content VARCHAR(500)', 'action_url VARCHAR(200)'],
    'exception_queue': ['title VARCHAR(100)', 'detail VARCHAR(1000)', 'priority VARCHAR(32)'],
    'knowledge_version': ["search_text TEXT GENERATED ALWAYS AS (CONCAT_WS(' ', JSON_UNQUOTE(JSON_EXTRACT(content, '$.title')), JSON_UNQUOTE(JSON_EXTRACT(content, '$.summary')), JSON_UNQUOTE(JSON_EXTRACT(content, '$.keywords')), JSON_UNQUOTE(JSON_EXTRACT(content, '$.body')))) STORED", 'FULLTEXT KEY ft_knowledge_search(search_text) WITH PARSER ngram'],
}


def canonical():
    spec = (ROOT / 'docs/specs/06-mysql-ddl-and-migrations.md').read_text(encoding='utf-8')
    section7 = spec.split('## SQL-007 ')[1].split('## SQL-008 ')[0]
    section10 = spec.split('## SQL-010 ')[1]
    definitions = tables(section10 + '\n' + section7)
    assert len(definitions) == 41, len(definitions)
    definitions = {name:ddl for name,ddl in definitions.items() if name in IMPLEMENTED}
    for name, additions in EXTRAS.items():
        ddl = definitions[name]
        pos = ddl.rindex(') ENGINE=')
        definitions[name] = ddl[:pos].rstrip() + ',\n -- Reviewed compatibility/projection fields; see specs/11.\n ' + ',\n '.join(additions) + '\n' + ddl[pos:]
    # Emit all columns as separate lines, making the reviewed baseline easy to compare.
    definitions = {name: re.sub(r'--[^\n]*\n', '', ddl) for name, ddl in definitions.items()}
    legacy = tables((DB/'tests/fixtures/main-388f51d-schema.sql').read_text(encoding='utf-8'))
    definitions.update({name:ddl for name,ddl in legacy.items() if name not in IMPLEMENTED and name != 'user'})
    return definitions


def write_baseline():
    header = "-- Generated by db/tools/build_schema.py from SQL-007 + SQL-010.\n-- Fresh empty database only. Existing main installations use db/migration.\nCREATE DATABASE IF NOT EXISTS it_ticket_system CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\nUSE it_ticket_system;\nSET NAMES utf8mb4;\nSET time_zone = '+00:00';\n\n"
    (DB / 'init/00-schema.sql').write_text(header + '\n\n'.join(canonical().values()) + '\n', encoding='utf-8')


if __name__ == '__main__':
    write_baseline()
